const Libro = require ('../api/models/libro.model')
const mongoose = require('mongoose');

const arrayLibros = [
    {
        "Portada":"https://imagessl0.casadellibro.com/a/l/t7/90/9788419536990.jpg",
        "Nombre":"MIDNIGHT MONOLOGUE",
        "Autor":"JYANOME",
        "Genero":["Manga"],
        "Descripcion":"Shion Yoshino se muere por tener un romance al más puro estilo shôjo. ¡Su objetivo en bachillerato es echarse un novio guapísimo! Aunque está dejándose la piel, no hay quien le saque de la soltería, y, para colmo, al apuntarse al club de cine,lleno de chi",
        "Valoracion": 0,
        "Resena":[],
    },{
        "Portada":"https://imagessl6.casadellibro.com/a/l/t7/76/9788419536976.jpg",
        "Nombre":"MADK, VOL. 1",
        "Autor":"RYO SUZURI",
        "Genero":["Manga"],
        "Descripcion":"Por culpa de sus peculiares fetiches sexuales, Makoto lleva mucho tiempo considerado un paria. Un día, encuentraun libro sobre invocación de demonios y, aunque al principio no tiene mucha fe en que funcione, consigue invocaral Archiduque J, un aristócrata",
        "Valoracion":0,
        "Resena":[],
    },{
        "Portada":"https://imagessl2.casadellibro.com/a/l/t7/02/9788419914002.jpg",
        "Nombre":"BLUE SKY COMPLEX 5",
        "Autor":"KEI ICHIKAWA",
        "Genero":["Manga"],
        "Descripcion":"El alivio por haber solucionado los problemas con Kurisu dura muy poco. La aparición de Kirara, una chica a la que Narasaki da clases particulares, altera el ambiente una vez más. El vínculo entre la pareja es más fuerte que nunca,pero las palabras de una",
        "Valoracion":0,
        "Resena":[],
    },{
        "Portada":"https://imagessl3.casadellibro.com/a/l/t7/83/9788419536983.jpg",
        "Nombre":"BOY´S ABYSS 10",
        "Autor":"RYO MINENAMI",
        "Genero":["Manga"],
        "Descripcion":"Su familia, su profesora, sus amigos de la infancia, una idol,un escritor y el pueblo donde vive... Reiji Kurose vive pasivamente atado por todo ello. No obstante, decide marcharse con sus dos viejos amigos a Tokio para poder escapar. Allí se reencuentr",
        "Valoracion":0,
        "Resena":[],
    },{
        "Portada":"https://imagessl1.casadellibro.com/a/l/t7/31/9788419869531.jpg",
        "Nombre":"JOJO S BIZARRE ADVENTURE PARTE 7: STEEL BALL RUN 16",
        "Autor":"HIROHIKO ARAKI",
        "Genero":["Manga"],
        "Descripcion":"Llega una de las partes más esperadas de Jojo: STEEL BALL RUN! Un importante cambio del mundo de Jojo, que reimagina personajes y crea situaciones más locas que nunca (¡sí, eso es posible!). La historia nos traslada al año 1890, en la que se va a celebrar una carrera a caballo que atravesará Estados unidos desde San Diego hasta Nueva York llamada Steel Ball Run. Johnny Joestar, un experto jinete que sufrió una herida de bala que lo dejó paralítico, decide participar en ella después de encontrarse con el enigmático Gyro Zeppeli y ver su extraño poder. Su ansia por descubrir el misterio del poder de Gyro, hará que se enfrenten en la carrera, pero pronto tendrán que colaborar para enfrentarse a los duros competidores que les pondrán las cosas más que difíciles. ¡¡EDICIÓN DELUXE CON NUEVO DISEÑO, LACA UV SECTORIZADA Y TINTA METALIZADA TANTO EN SOBRECUBIERTA COMO EN CUBIERTA Y DORSO!!",
        "Valoracion":0,
        "Resena":[],
    },{
        "Portada":"https://imagessl5.casadellibro.com/a/l/t7/45/9788419412645.jpg",
        "Nombre":"EL CHICO Y EL PERRO",
        "Autor":"TAKASHI MURAKAMI, HASE SEISHU",
        "Genero":["Manga"],
        "Descripcion":"Tras el tsunami de 2011, un hombre encuentra un pastor alemán callejero que se convierte en su fiel compañero y el de su madre, quien sufre demencia. Sin embargo, un día el joven muere en un accidente de tráfico y el animal es adoptado por otra persona, un ladrón. A lo largo de la historia, este perro hará de guardián para varios dueños, hasta encontrarse con su último amo, un niño que llevaba todo este tiempo buscándolo. Un emotivo relato que recorre Japón desde la zona afectada de Tohoku hasta Kyushu, mientras se cuenta la historia del epico viaje de un perro y sus diferentes cuidadores.",
        "Valoracion":0,
        "Resena":[],
    },{
        "Portada":"https://imagessl3.casadellibro.com/a/l/t7/03/9788411402903.jpg",
        "Nombre":"MERMAID SAGA Nº 03/03",
        "Autor":"RUMIKO TAKAHASHI",
        "Genero":["Manga"],
        "Descripcion":"Un día de hace cien años, en una imponente mansión, dos hermanos se suicidaron tomándose un misterioso veneno. ¡Pero resulta que ese veneno era nada menos que el que contiene la carne de sirena, capaz de conceder la inmortalidad solo a unos pocos! El hermano pequeño resucitó, pero parece que la pobre hermana mayor no corrió la misma suerte...¡Cuando el pasado de los hermanos sale a la luz, un horror indescriptible se cierne sobre la mansión!",
        "Valoracion":0,
        "Resena":[],
    },{
        "Portada":"https://imagessl4.casadellibro.com/a/l/t7/64/9788419760364.jpg",
        "Nombre":"JUNJI ITO, TERROR DESPEDAZADO 1 DE 28",
        "Autor":"JUNJI ITO",
        "Genero":["Manga"],
        "Descripcion":"Tras conocerse a través de una página web, cuatro personas deciden emprender un viaje para alcanzar un objetivo común: poner fin a sus vidas. Extraño caso de suicidio colectivo en forma de thriller sobrenatural que reformula el mito del doppelgänger.  Junto a Black Paradox, en este volumen encontrarás las historias cortas de La lamedora, en el que conoceremos a una extraña mujer que envenena a sus victimas con su grotesca y desagradable lengua, y El pabellón de lo paranormal, donde visitaremos una perturbadora e inquietante exposición universal.  Sumérgete en el terrorífico mundo de Junji Ito con este coleccionable donde te adentrarás en la mente de nuestro maestro del terror favorito.",
        "Valoracion":0,
        "Resena":[],
    },{
        "Portada":"https://imagessl6.casadellibro.com/a/l/t7/96/9788419290496.jpg",
        "Nombre":"BARRERAS DEL CORAZON 3",
        "Autor":"MIKA",
        "Genero":["Manga"],
        "Descripcion":"Yamato no puede más. Los celos, la posesividad, su deseo por ser algo más que el mejor amigo de Kakeru... le están comiendo por dentro. Pero tiene miedo de perder a su compañero si le confiesa la verdad: lleva enamorado de el desde siempre. Tras ver lo que parecía, a simple vista, una cita entre Kakeru y Akane, Yamato se deja llevar y abraza a Kakeru, creando un momento incómodo entre ellos y provocando que se distancien aún más. Sin embargo, no hay tiempo para recuperar el equilibrio antes de viajar a Kioto... y todo queda envuelto en una sensación de incertidumbre. ¿Ayudará el viaje a que confiesen sus sentimientos? ¿O los deseos de ambos seguirán sin salir a la luz?",
        "Valoracion":0,
        "Resena":[],
    },{
        "Portada":"https://imagessl4.casadellibro.com/a/l/t7/74/9788411402774.jpg",
        "Nombre":"LA CAJA AZUL Nº 03",
        "Autor":"KOJI MIURA",
        "Genero":["Manga"],
        "Descripcion":"Hina se siente presionada por las personas que la rodean y está más y más agobiada conforme se acerca el día de disputar su torneo. Cuando se siente abrumada por la ansiedad, mira a Taiki, quien siempre está ahí... Y a la vez, comienzan los partidos clasificatorios de la prefectura. Los resultados de su entrenamiento sin descanso se ponen a prueba en los partidos a dobles contra el poderoso instituto Sajikawa.",
        "Valoracion":0,
        "Resena":[],
    },{
        "Portada":"https://imagessl1.casadellibro.com/a/l/t7/41/9788418945441.jpg",
        "Nombre":"ESTOY GENIAL, GRACIAS",
        "Autor":"MONICA HEISEY",
        "Genero":["Narrativa de humor"],
        "Descripcion":"Maggie está bien. Está genial, gracias. Bueno, claro, no tiene un duro, su tesis doctoral está estancada y su matrimonio solo ha durado 608 días, pero a la madura edad de veintinueve años, está decidida a aprovechar su nueva vida como La Divorciada Más Joven de la Historia.",
        "Valoracion":0,
        "Resena":[],
    },{
        "Portada":"https://imagessl9.casadellibro.com/a/l/t7/69/9788418153969.jpg",
        "Nombre":"PARA LEER MIENTRAS SUBE EL ASCENSOR",
        "Autor":"ENRIQUE JARDIEL PONCELA",
        "Genero":["Narrativa de humor"],
        "Descripcion":"Estos 84 textos forman parte de la antología que en 1948 hizo Jardiel, recopilando en un único volumen una serie de trabajos cortos que había publicado durante los años veinte en diversas revistas cómicas como Buen Humor o Gutiérrez. Lo tituló para leer mientras sube el ascensor, haciendo referencia a la brevedad de los textos y satirizando a la vez lo mucho que tardaban los ascensores en llegar a su destino en aquellos años.",
        "Valoracion":0,
        "Resena":[],
    },{
        "Portada":"https://imagessl8.casadellibro.com/a/l/t7/38/9788412669138.jpg",
        "Nombre":"HISTORIA COMICA DE LA MUERTE",
        "Autor":"ENRIQUE GALLUD JARDIEL",
        "Genero":["Narrativa de humor"],
        "Descripcion":"La muerte es la cosa más democrática que existe. Muchos humanos no sabemos ortografía ni resolver ecuaciones, pero todos sabemos morirnos. Además, hemos estado durante muchos siglos obsesionados por la idea de que un día vendría a vernos esa señora (o señor: no estamos seguros) con una guadaña de esas que se usan para cortar cereales. Para quitarnos ese inútil temor a lo inevitable se ha escrito este libro: para reírnos nosotros de la muerte antes de que ella se ría de nosotros, para desdramatizarla y disfrutar un poco con este humor, que no por negro es menos valioso. En esta obra se da una visión humorística de la muerte en las distintas culturas y un simpatiquísimo popurrí de temas relacionados con la Parca: suicidios, fantasmas, costumbres raras, óbitos curiosos, entrevistas con muertos, descripciones de asesinos y muchas otras estupideces que harán al lector pasar un buen rato a costa de esa señora chupada y huesuda que tanto se empeña en asustarnos.",
        "Valoracion":0,
        "Resena":[],
    },{
        "Portada":"https://imagessl3.casadellibro.com/a/l/t7/03/9788412696103.jpg",
        "Nombre":"EL PUENTE DE LOS PERROS SUICIDAS",
        "Autor":"ABEL AMUTXATEGI",
        "Genero":["Narrativa de humor"],
        "Descripcion":"Nueva Orleans, 2021. John Kennedy Toole se revuelve en un montón de basura. Sí, lo han adivinado. El mayor genio literario de Luisiana acaba de volver a la vida en una ciudad hostil que, paradójicamente, lo idolatra. Mientras intenta comprender su nueva realidad y saborear por fin la gloria literaria que solo se le concedió a su muerte, el autor de La conjura de los necios se adentra en un mundillo literario exento de teología y geometría que lo repudia abiertamente. ",
        "Valoracion":0,
        "Resena":[],
    },{
        "Portada":"https://imagessl6.casadellibro.com/a/l/t7/16/9788418040016.jpg",
        "Nombre":"NOSTALGIA MILENIAL",
        "Autor":"NOSTALGIA MILENIAL",
        "Genero":["Narrativa de humor"],
        "Descripcion":"Con este libro podrás recordar los desayunos con Megatrix, las tardes en el ciber, las canciones del verano o la llegada del Tuenti. También los politonos, el fenómeno Harry Potter o el primer OT. Podrás recordar lo maravilloso que fue crecer en pleno cambio de milenio.",
        "Valoracion":0,
        "Resena":[],
    },{
        "Portada":"https://imagessl2.casadellibro.com/a/l/t7/82/9788417375782.jpg",
        "Nombre":"LOS ARBOLES",
        "Autor":"PERCIVAL EVERETT",
        "Genero":["Narrativa de humor"],
        "Descripcion":"¿Es posible reírse al tiempo que se toma conciencia de estar leyendo una historia absolutamente oscura y aterradora? Percival Everett lo consigue con Los árboles. En esta novela, finalista del Booker Prize 2022 y aclamada por la crítica, el escritor resucita a las víctimas de los linchamientos racistas en Estados Unidos a lo largo del tiempo y demuestra que el veneno del odio, lejos de haber desaparecido, está en auge. Novela policiaca, comedia mordaz, caricatura del supremacismo blanco",
        "Valoracion":0,
        "Resena":[],
    },{
        "Portada":"https://imagessl5.casadellibro.com/a/l/t7/05/9788401021305.jpg",
        "Nombre":"EL PACIENTE SIEMPRE LLAMA DOS VECES",
        "Autor":"ENFERMERA SATURADA",
        "Genero":["Narrativa de humor"],
        "Descripcion":"Queridas Nightingales: Nos ha tocado vivir la profesión más bonita del mundo, esa que nos hace dar más vueltas que un vendaje compresivo, esa que una ejerce las 24 horas, sobre todo cuando tus amigas tienen su primer hijo o cuando tu prima quiere saber si puede mezclar antibióticos y alcohol. Os presento mis nuevas aventuras como enfermera eventual en Madrid.»",
        "Valoracion":0,
        "Resena":[],
    },{
        "Portada":"https://imagessl6.casadellibro.com/a/l/t7/56/9788494933356.jpg",
        "Nombre":"EL POWER RANGER ROSA",
        "Autor":"CHRISTO CASAS",
        "Genero":["Narrativa de humor"],
        "Descripcion":"Un joven español da tumbos por Berlín. En su teléfono conviven apps para buscar piso, trabajo y sexo. Su abuela también emigró a Alemania, pero acabó volviendo al pueblo para formar una familia. Allí es testigo de cómo su nieto hace dos descubrimientos: que es marica y que es pobre.",
        "Valoracion":0,
        "Resena":[],
    },{
        "Portada":"https://imagessl4.casadellibro.com/a/l/t7/94/9788413854694.jpg",
        "Nombre":"LOS JUBILADOS LOS CARGA EL DIABLO",
        "Autor":"LUIS CHACON DE LA TORRE",
        "Genero":["Narrativa de humor"],
        "Descripcion":"A Alfonsito (Pochele) se le viene el mundo encima cuando, en plenas vacaciones estivales, sus padres lo dejan un mes con su abuelo, pero no con el de ciudad (el urbanita), sino con el rural (el gañán), el que vive en una quintería, a las afueras de Cacerorilla. Se llama Tiburcio (alias “Atrancapoco”), y apenas lo visitan, no sea que se le “peguen” sus modales de paleto al niño. ",
        "Valoracion":0,
        "Resena":[],
    },{
        "Portada":"https://imagessl7.casadellibro.com/a/l/t7/97/9788427049697.jpg",
        "Nombre":"ACADEMIA DE MADRES: EL ORIGEN",
        "Autor":"NACHTER",
        "Genero":["Narrativa de humor"],
        "Descripcion":"odo sobre lanzamiento de chancla y otras técnicas ancestrales de maternidad. Madre está harta de que las técnicas ancestrales de la maternidad se estén perdiendo. Pero eso se va a acabar. Ella va a poner orden: ha fundado la Academia de Madres, donde compartirá con otras madres ávidas de sabiduría todos sus conocimientos, desde el legendario lanzamiento de chancla hasta las frasecitas de madre.",
        "Valoracion":0,
        "Resena":[],
    },{
        "Portada":"https://imagessl5.casadellibro.com/a/l/t7/55/9788402423955.jpg",
        "Nombre":"MORTADELO Y FILEMON: MUNDIAL DE BALONCESTO 2023",
        "Autor":"FRANCISCO IBAÑEZ",
        "Genero":["Infantil"],
        "Descripcion":"En esta nueva aventura de Mortadelo y Filemón, el Súper les encarga una misión en el campeonato del mundo de baloncesto 2023.",
        "Valoracion":0,
        "Resena":[],
    },{
        "Portada":"https://imagessl9.casadellibro.com/a/l/t7/49/9788498569049.jpg",
        "Nombre":"EL CLUB DE CÓMIC DE CHIKIGATO 4: COLABORACIONES",
        "Autor":"DAV PILKEY",
        "Genero":["Infantil"],
        "Descripcion":"Las ranas unidas, jamás serán vencidas. A veces, las cosas más pequeñas, pueden marcar una gran diferencia.",
        "Valoracion":0,
        "Resena":[],
    },{
        "Portada":"https://imagessl8.casadellibro.com/a/l/t7/68/9788419638168.jpg",
        "Nombre":"SARA Y JAMILA SALVAN EL VERANO",
        "Autor":"GILLIAN GOERZ",
        "Genero":["Infantil"],
        "Descripcion":"Jamila espera un verano solitario en su barrio nuevo. Hasta que conoce a Sara Bones. Sara es un poco rara, pero ambas necesitan un plan para el verano y se hacen amigas.",
        "Valoracion":0,
        "Resena":[],
    },{
        "Portada":"https://imagessl8.casadellibro.com/a/l/t7/48/9788419110848.jpg",
        "Nombre":"EL MUNDO DE FRANKIE",
        "Autor":"AOIFE DOOLEY",
        "Genero":["Infantil"],
        "Descripcion":"Frankie es diferente al resto de los niños de su clase, y no sabe por qué. Le encanta la música rock, le cuesta concentrarse, y sus compañeros se burlan de ella porque no conoce a su padre. ¿Será porque es una marciana? ",
        "Valoracion":0,
        "Resena":[],
    },{
        "Portada":"https://imagessl3.casadellibro.com/a/l/t7/23/9788419760623.jpg",
        "Nombre":"LAS AVENTURAS DE BATMAN Y ROBIN 16",
        "Autor":"TY TEMPLETON",
        "Genero":["Infantil"],
        "Descripcion":"¡A Catwoman la están acusando de robos que no ha cometido! Pero… Si no ha sido ella, ¿quien? La ladrona más famosa de Gotham debe trabajar con Batman y Robin para limpiar su nombre.",
        "Valoracion":0,
        "Resena":[],
    },{
        "Portada":"https://imagessl3.casadellibro.com/a/l/t7/23/9788408274223.jpg",
        "Nombre":"LAS PRINCESAS REBELDES 5: EL MISTERIO DE AURAX",
        "Autor":"ROBERTO SANTIAGO",
        "Genero":["Infantil"],
        "Descripcion":"Las Princesas Rebeldes son mucho más que un grupo de princesas y príncipes herederos al trono. Desde que cumplieron once años... ¡tienen superpoderes!",
        "Valoracion":0,
        "Resena":[],
    },{
        "Portada":"https://imagessl7.casadellibro.com/a/l/t7/87/9788419102287.jpg",
        "Nombre":"12. EL CAPITAN CALZONCILLOS Y LA TURBULENTA AVENTURA DE DON TUFOTE ",
        "Autor":"DAV PILKEY",
        "Genero":["Infantil"],
        "Descripcion":"Jorge y Berto, mano a mano con sus dobles del pasado, han descubierto algo que huele peor que un montón de calcetines podridos. Su profesor de gimnasia, el señor Magrazas, ha creado el Tont-o-Niño 2000, un spray maloliente de control mental que transforma a los chavales, haciendolos atentos, obedientes y perfectos. ",
        "Valoracion":0,
        "Resena":[],
    },{
        "Portada":"https://imagessl8.casadellibro.com/a/l/t7/38/9788419421838.jpg",
        "Nombre":"ARTA EN EL TSUNAMI MAXIMO",
        "Autor":"ARTA GAME",
        "Genero":["Infantil"],
        "Descripcion":"Arta y sus amigos tienen que encontrar la forma de pararles los pies. Pero para eso tendrán que aprender a pilotar una nave, enfrentarse a peces radioactivos y sobrevivir a un tsunami máximo.",
        "Valoracion":0,
        "Resena":[],
    },{
        "Portada":"https://imagessl2.casadellibro.com/a/l/t7/52/9788419421852.jpg",
        "Nombre":"BUSCAPISTAS 15: EL CASO DEL HECHIZO MUSICAL",
        "Autor":"TERESA BLANCH",
        "Genero":["Infantil"],
        "Descripcion":"¡En Basketville se estrena una nueva función! Pero cuando suena la música, el público empieza a desconectar como si estuviera hipnotizado, y Pepay Maxi lo tienen claro: ¡alguien está detrás de ese hechizo musical! ¿Quien puede ser el responsable y por que? ¡Únete a los detectives y resuelve un caso mágico!",
        "Valoracion":0,
        "Resena":[],
    },{
        "Portada":"https://imagessl3.casadellibro.com/a/l/t7/73/9788427234673.jpg",
        "Nombre":"NINJA KID 11 - ¡NINJAS ARTISTAS!",
        "Autor":"ANH DO",
        "Genero":["Infantil"],
        "Descripcion":"La clase de Nelson prepara ¡un CONCURSO DE PINTURA! Pero, por error, Nelson y su primo Kenny viajan en el tiempo y, en vez de pintar criaturas mitológicas en sus cuadros, acaban LUCHANDO contra ellas.",
        "Valoracion":0,
        "Resena":[],
    },{
        "Portada":"https://imagessl3.casadellibro.com/a/l/t7/33/9788418668333.jpg",
        "Nombre":"LA CHICA QUE VIVE AL FINAL DEL CAMINO",
        "Autor":"LAIRD KOENIG",
        "Genero":["Novela de Terror"],
        "Descripcion":"na obra maestra del gótico americano. Una novela de culto, tensa y aterradora, que inspiró la película protagonizada por Martin Sheen y por una jovencísima Jodie Foster.",
        "Valoracion":0,
        "Resena":[],
    },{
        "Portada":"https://imagessl9.casadellibro.com/a/l/t7/99/9788445014899.jpg",
        "Nombre":"VENDIMOS NUESTRAS ALMAS",
        "Autor":"GRADY HENDRIX",
        "Genero":["Novela de Terror"],
        "Descripcion":"Un viaje épico hacia el corazón de un país paranoico dominado por las pastillas y las conspiraciones que parece haber perdido su propia alma.",
        "Valoracion":0,
        "Resena":[],
    },{
        "Portada":"https://imagessl6.casadellibro.com/a/l/t7/06/9788445012406.jpg",
        "Nombre":"ASCENSIÓN",
        "Autor":"NICHOLAS BINGE",
        "Genero":["Novela de Terror"],
        "Descripcion":"Una enorme montaña cubierta de nieve ha aparecido en el Océano Pacífico. Nadie sabe exactamente cuándo apareció, qué tan grande podría ser o cómo explicar su existencia. Cuando Harold Tunmore, un científico de fenómenos misteriosos, es contactado por una organización en la sombra para ayudar a investigar, no tiene idea de en qué se está metiendo mientras él y su equipo parten hacia la montaña.",
        "Valoracion":0,
        "Resena":[],
    },{
        "Portada":"https://imagessl0.casadellibro.com/a/l/t7/20/9788445013120.jpg",
        "Nombre":"GRUPO DE APOYO PARA FINAL GIRLS",
        "Autor":"GRADY HENDRIX",
        "Genero":["Novela de Terror"],
        "Descripcion":"En las películas de miedo, las Final Girls son las que han quedado con vida cuando empiezan a pasar los títulos de créditos. Han sobrevivido a la peor noche de su vida, sí, pero…¿qué sucede luego?",
        "Valoracion":0,
        "Resena":[],
    },{
        "Portada":"https://imagessl6.casadellibro.com/a/l/t7/36/9788415618836.jpg",
        "Nombre":"DRACULA (CLÁSICOS ILUSTRADOS)",
        "Autor":"BRAM STOKER",
        "Genero":["Novela de Terror"],
        "Descripcion":"Las de Bram Stoker y Jonathan Harker fueron vidas paralelas. Stoker era el secretario particular de Henry Irving, un reputado actor shakespeariano y propietario del Lyceum Theatre de Londres; Harker, el del enigmático conde Drácula, quien lo convocó a su castillo de Transilvania para negociar la adquisición de una mansión en Londres. No es casual que el personaje de Drácula se inspire en las facciones e idiosincrasia de Irving, ni que Stoker hiciese una lectura pública en el Lyceum Theatre días antes de su edición.",
        "Valoracion":0,
        "Resena":[],
    },{
        "Portada":"https://imagessl9.casadellibro.com/a/l/t7/99/9788419654199.jpg",
        "Nombre":"LA REVELADORA",
        "Autor":"DARYL GREGORY",
        "Genero":["Novela de Terror"],
        "Descripcion":"Stella Birch huyó de su hogar hace mucho tiempo. Hoy es una mujer autosuficiente: destila whisky de contrabando junto al único hombre negro del pueblo. Eso le ha enseñado a mantenerse oculta. Su familia lleva diez años sin saber de ella.",
        "Valoracion":0,
        "Resena":[],
    },{
        "Portada":"https://imagessl0.casadellibro.com/a/l/t7/10/9788415932710.jpg",
        "Nombre":"ESPAÑA: GUERRA ZOMBI",
        "Autor":"JAIME NOGUERA",
        "Genero":["Novela de Terror"],
        "Descripcion":"Alejandro Noriega, un mediocre escritor español, es requerido desde su refugio en un archipiélago noruego para redactar un informe de la ONU sobre la Guerra Zombi en España. Sus reticencias iniciales para viajar a la Península Ibérica, ocupada todavía en gran parte por las hordas de muertos vivientes, desaparecen cuando, junto a una jugosa cantidad económica, se le ofrece conocer el paradero de su familia, desaparecida durante la fase inicial de la pandemia.",
        "Valoracion":0,
        "Resena":[],
    },{
        "Portada":"https://imagessl5.casadellibro.com/a/l/t7/95/9788494836695.jpg",
        "Nombre":"LA MALDICIÓN DE HILL HOUSE",
        "Autor":"SHIRLEY JACKSON",
        "Genero":["Novela de Terror"],
        "Descripcion":"uatro personajes llegan a un viejo y laberíntico caserón conocido como Hill House. Son el doctor Montague, un estudioso de lo oculto que busca pruebas de fenómenos psíquicos en casas encantadas, y tres personas a quienes el doctor ha reclutado para llevar a cabo un experimento.",
        "Valoracion":0,
        "Resena":[],
    },{
        "Portada":"https://imagessl6.casadellibro.com/a/l/t7/46/9788494995446.jpg",
        "Nombre":"UN DESCANSO PARA LOS MUERTOS Y OTROS RELATOS.",
        "Autor":"LUCY TAYLOR",
        "Genero":["Novela de Terror"],
        "Descripcion":"Esta es una antología ecléctica en todos sus aspectos. En la temática, aunque predomina el terror, no hay un hilo conductor, y puedes encontrar el relato de una familia que habita una casa sumergida junto a otro acerca de una figura mitológica y misteriosa. Y, en cuanto al estilo, en estas doce historias —escritas entre 1991 y 2018— podemos comprobar cómo es capaz de alternar entre un tono rudo y coloquial y la escritura más poética y literaria.",
        "Valoracion":0,
        "Resena":[],
    },{
        "Portada":"https://imagessl6.casadellibro.com/a/l/t7/26/9788496509726.jpg",
        "Nombre":"LA CONDESA SANGRIENTA",
        "Autor":"ALEJANDRA PIZARNIK",
        "Genero":["Novela de Terror"],
        "Descripcion":"Sentada en su trono, la condesa mira torturar y oye gritar. Sus viejas y horribles sirvientas son figuras silenciosas que traen fuego, cuchillos, agujas, atizadores; que torturan muchachas, que luego las entierran. ",
        "Valoracion":0,
        "Resena":[],
    },{
        "Portada":"https://imagessl6.casadellibro.com/a/l/t7/46/9788491297246.jpg",
        "Nombre":"COMO (NO) ESCRIBI NUESTRA HISTORIA",
        "Autor":"ELISABET BENAVENT",
        "Genero":["Novela romática"],
        "Descripcion":"Decidida a huir para volver a abrazar la escritura, se topa con Darío, un músico recien llegado de París que además es su vecino. Empieza así una nueva historia en la que Elsa es la protagonista. ¿Será capaz de contarlo todo?",
        "Valoracion":0,
        "Resena":[],
    },{
        "Portada":"https://imagessl0.casadellibro.com/a/l/t7/00/9788418945700.jpg",
        "Nombre":"LA TEORÍA DEL AMOR",
        "Autor":"ALI HAZELWOOD",
        "Genero":["Novela romática"],
        "Descripcion":"as múltiples vidas de la física teórica Elsie Hannaway han acabado atrapándola. De día es profesora adjunta. Se afana en corregir exámenes y enseñar termodinámica con la esperanza de, algún día, conseguir la titularidad. ",
        "Valoracion":0,
        "Resena":[],
    },{
        "Portada":"https://imagessl6.casadellibro.com/a/l/t7/66/9788408274766.jpg",
        "Nombre":"¿Y A TI QUE TE PICA?",
        "Autor":"MEGAN MAXWELL",
        "Genero":["Novela romática"],
        "Descripcion":"Nacho Duarte es un reconocido director de cine mexicano que, tras la muerte de su esposa, cerró las puertas de su corazón a cal y canto. Le gusta disfrutar con las mujeres, pero no suele repetir con la misma porque no piensa volver a enamorarse.",
        "Valoracion":0,
        "Resena":[],
    },{
        "Portada":"https://imagessl3.casadellibro.com/a/l/t7/63/9788466672863.jpg",
        "Nombre":"ÉXTASIS",
        "Autor":"NOEMI CASQUET",
        "Genero":["Novela romática"],
        "Descripcion":"Amisha tiene el don de ver el futuro cada vez que llega al orgasmo, lo que se ha convertido en una jodida maldición. Cuando decide librarse de ella, hace las maletas y viaja a Bali, el lugar donde todo comenzó. ",
        "Valoracion":0,
        "Resena":[],
    },{
        "Portada":"https://imagessl2.casadellibro.com/a/l/t7/52/9788401028052.jpg",
        "Nombre":"ATLAS: LA HISTORIA DE PA SALT ",
        "Autor":"LUCINDA RILEY",
        "Genero":["Novela romática"],
        "Descripcion":"Un chico es encontrado momentos antes de su muerte y acogido por una cariñosa familia. Dulce, precoz y lleno de talento, el niño florece en su nuevo hogar y la familia le muestra una vida que no había creído posible. Perose niega a decir una palabra sobre quién es realmente.",
        "Valoracion":0,
        "Resena":[],
    },{
        "Portada":"https://imagessl1.casadellibro.com/a/l/t7/81/9788408269281.jpg",
        "Nombre":"DONDE TODO BRILLA",
        "Autor":"ALICE KELLEN",
        "Genero":["Novela romática"],
        "Descripcion":"Nicki Aldrich y River Jackson han sido inseparables desde que llegaron al mundo con cuarenta y siete minutos de diferencia. Ella lo hizo envuelta en polvo de hadas. Él como si fuese un meteoro en llamas. ",
        "Valoracion":0,
        "Resena":[],
    },{
        "Portada":"https://imagessl8.casadellibro.com/a/l/t7/38/9788419501738.jpg",
        "Nombre":"HOOKED: UNA HISTORIA DE NUNCA JAMAS.",
        "Autor":"EMILY MCINTIRE",
        "Genero":["Novela romática"],
        "Descripcion":"ames ha tenido siempre un único objetivo: acabar con Peter Michaels, su enemigo. Un día, la hija de Peter, Wendy, de solo veinte años, entra en el bar de James y este ve la ocasión: la seducirá y la utilizará para vengarse. ",
        "Valoracion":0,
        "Resena":[],
    },{
        "Portada":"https://imagessl9.casadellibro.com/a/l/t7/49/9788408271949.jpg",
        "Nombre":"EL COLOR DE LAS COSAS INVISIBLES",
        "Autor":"ANDREA LONGARELA",
        "Genero":["Novela romática"],
        "Descripcion":"Primero en el instituto, luego en un concierto e, inesperadamente, tambien unos años despues, cuando ya creían que no volverían a encontrarse. Incluso se ven empujados a compartir una noche en una casa perdida en mitad del bosque.",
        "Valoracion":0,
        "Resena":[],
    },{
        "Portada":"https://imagessl8.casadellibro.com/a/l/t7/28/9788408267928.jpg",
        "Nombre":"EL ARTE DE SER NOSOTROS",
        "Autor":"INMA RUBIALES",
        "Genero":["Novela romática"],
        "Descripcion":"Leah nunca se ha sentido la protagonista de la suya. Vive con la cabeza enterrada en los libros, intentando pasar desapercibida, y se refugia en la gran comunidad de lectores que tiene en internet.",
        "Valoracion":0,
        "Resena":[],
    },{
        "Portada":"https://imagessl2.casadellibro.com/a/l/t7/82/9788418945182.jpg",
        "Nombre":"LA HIPOTESIS DEL AMOR",
        "Autor":"ALI HAZELWOOD",
        "Genero":["Novela romática"],
        "Descripcion":"Olive Smith es una doctoranda de tercer año que no cree en las relaciones amorosas duraderas, pero su mejor amiga, Ahn, sí, y por eso Olive se ha metido en un lío monumental.",
        "Valoracion":0,
        "Resena":[],
    },{
        "Portada":"https://imagessl8.casadellibro.com/a/l/t7/48/9788401032448.jpg",
        "Nombre":"TORMENTA DE ESPADAS (CANCIÓN DE HIELO Y FUEGO 3)",
        "Autor":"GEORGE R.R. MARTIN",
        "Genero":["Narrativa fantástica"],
        "Descripcion":"Los cinco títulos hasta ahora publicados de «Canción de hielo y fuego», Juego de tronos, Choque de reyes, Tormenta de espadas, Festín de cuervos y Danza de dragones, llegan a las librerías en una nueva edición que conquistará tanto a los fans de esta saga épica como a aquellos que esperan la oportunidad perfecta para adentrarse en sus páginas por primera vez.",
        "Valoracion":0,
        "Resena":[],
    },{
        "Portada":"https://imagessl5.casadellibro.com/a/l/t7/25/2910026049625.jpg",
        "Nombre":"YUMI Y EL PINTOR DE PESADILLAS (NOVELA SECRETA 3)",
        "Autor":"BRANDON SANDERSON",
        "Genero":["Narrativa fantástica"],
        "Descripcion":"Yumi viene de una tierra de jardines, meditación y espíritus, mientras que Pintor vive en un mundo de oscuridad, tecnología y pesadillas. Cuando de pronto sus vidas se ven extrañamente entrelazadas, ¿podrán dejar de lado sus diferencias y colaborar para descubrir los misterios de su situación y salvar sus respectivas comunidades de un desastre seguro?",
        "Valoracion":0,
        "Resena":[],
    },{
        "Portada":"https://imagessl6.casadellibro.com/a/l/t7/56/9788445015056.jpg",
        "Nombre":"LA CAÍDA DE NÚMENOR",
        "Autor":"J.R.R. TOLKIEN",
        "Genero":["Narrativa fantástica"],
        "Descripcion":".R.R. Tolkien describió la Segunda Edad de la Tierra Media como una edad oscura, y no se cuenta (o no es necesario) mucho de su historia. ",
        "Valoracion":0,
        "Resena":[],
    },{
        "Portada":"https://imagessl8.casadellibro.com/a/l/t7/18/9788418037818.jpg",
        "Nombre":"TRENZA DEL MAR ESMERALDA (NOVELA SECRETA 1)",
        "Autor":"BRANDON SANDERSON",
        "Genero":["Narrativa fantástica"],
        "Descripcion":"En su isla natal sobre un océano verde esmeralda, la única vida que Trenza conoce es sencilla, marcada por el placer de coleccionar las tazas que traen los marineros de tierras lejanas y escuchar las historias que le cuenta su amigo Charlie. ",
        "Valoracion":0,
        "Resena":[],
    },{
        "Portada":"https://imagessl6.casadellibro.com/a/l/t7/76/9788418037276.jpg",
        "Nombre":"EL POZO DE LA ASCENSION",
        "Autor":"BRANDON SANDERSON",
        "Genero":["Narrativa fantástica"],
        "Descripcion":"La saga Nacidos de la Bruma (Mistborn) es una obra imprescindible del  Cosmere, el universo destinado a dar forma a la serie más extensa y fascinante jamás escrita en el ámbito de la fantasía épica.",
        "Valoracion":0,
        "Resena":[],
    },{
        "Portada":"https://imagessl0.casadellibro.com/a/l/t7/00/9788418037900.jpg",
        "Nombre":"LA GUIA DEL MAGO FRUGAL PARA SOBREVIVIR EN LA INGLATERRA DEL MEDIEVO",
        "Autor":"BRANDON SANDERSON",
        "Genero":["Narrativa fantástica"],
        "Descripcion":"Un hombre despierta en el claro de un bosque de lo que parece ser la Inglaterra medieval, sin ningún recuerdo sobre quién es, de dónde procede ni por qué está allí. Perseguido por un grupo llegado de su propia época, su única posibilidad de sobrevivir pasa por recuperar la memoria perdida, conseguir aliados entre la gente del lugar y quizás incluso confiaren sus supersticiosos alardes. ",
        "Valoracion":0,
        "Resena":[],
    },{
        "Portada":"https://imagessl0.casadellibro.com/a/l/t7/60/9788466675260.jpg",
        "Nombre":"REINO FEROZ",
        "Autor":"LUCIA G. SOBRADO",
        "Genero":["Narrativa fantástica"],
        "Descripcion":"Tras la caída del Hada Madrina, el malefi cio no se ha dispersado del todo. Las princesas no han despertado de su letargo y los secretos más oscuros de Lobo han salido a la luz, condenándolo para siempre: Roja no volverá a confiar en el.",
        "Valoracion":0,
        "Resena":[],
    },{
        "Portada":"https://imagessl2.casadellibro.com/a/l/t7/32/9788417347932.jpg",
        "Nombre":"EL RITMO DE LA GUERRA (EL ARCHIVO DE LAS TORMENTAS 4)",
        "Autor":"BRANDON SANDERSON",
        "Genero":["Narrativa fantástica"],
        "Descripcion":"Hay secretos que hemos guardado mucho tiempo. Vigilantes. Insomnes. Eternos. Y pronto dejarán de ser nuestros.",
        "Valoracion":0,
        "Resena":[],
    },{
        "Portada":"https://imagessl4.casadellibro.com/a/l/t7/74/9788416517374.jpg",
        "Nombre":"LA VIDA INVISIBLE DE ADDIE LARUE",
        "Autor":"V.E. SCHWAB",
        "Genero":["Narrativa fantástica"],
        "Descripcion":"Una historia que nunca olvidarás.Tras hacer un pacto con el diablo, Addie entrega su alma a cambio de la inmortalidad. Sin embargo, ningún trato faustiano está exento de consecuencias: el diablo le entregará la inmortalidad que tanto desea, pero le quitará algo que ella anhelará durante toda su existencia: la posibilidad de ser recordada.",
        "Valoracion":0,
        "Resena":[],
    },{
        "Portada":"https://imagessl3.casadellibro.com/a/l/t7/33/9788418037733.jpg",
        "Nombre":"EL METAL PERDIDO (NACIDOS DE LA BRUMA [MISTBORN] 7)",
        "Autor":"BRANDON SANDERSON",
        "Genero":["Narrativa fantástica"],
        "Descripcion":"Waxillium Ladrian, vigilante de la ley convertido en senador de la gran  ciudad, lleva años intentando dar caza a la sombría organización llamada  el Grupo -entre cuyos líderes se cuentan su difunto tío y su hermana-,  desde que empezaron a secuestrar a personas con el poder de la alomancia  en su linaje. ",
        "Valoracion":0,
        "Resena":[],
    },{
        "Portada":"https://imagessl7.casadellibro.com/a/l/t7/87/9788408275787.jpg",
        "Nombre":"LA REBELION DE LOS BUENOS (PREMIO FERNANDO LARA 2023)",
        "Autor":"ROBERTO SANTIAGO",
        "Genero":["Novela negra"],
        "Descripcion":"Fátima Montero, propietaria de uno de los emporios farmacéuticos más poderosos del mundo, contrata al irreverente abogado Jeremías Abi para que se encargue de su multimillonario divorcio. Herida en su orgullo después de saber que su marido y socio tiene una relación amorosa con una menor, solo desea destruirle, pero algo muy turbio se esconde bajo ese encargo.",
        "Valoracion":0,
        "Resena":[],
    },{
        "Portada":"https://imagessl3.casadellibro.com/a/l/t7/23/9788408270423.jpg",
        "Nombre":"EL ANGEL DE LA CIUDAD (SERIE KRAKEN 2)",
        "Autor":"EVA GARCIA SAENZ DE URTURI",
        "Genero":["Novela negra"],
        "Descripcion":"Un espléndido y decadente palazzo arde en una pequeña isla veneciana donde se celebra un encuentro de la Liga de Libreros Anticuarios. Los cuerpos de los invitados, todos conocidos de Kraken, no aparecen entre los escombros, y se sospecha que su madre, Ítaca, estuvo implicada en el incendio que sucedió en idénticas circunstancias décadas atrás.",
        "Valoracion":0,
        "Resena":[],
    },{
        "Portada":"https://imagessl6.casadellibro.com/a/l/t7/06/9788419638106.jpg",
        "Nombre":"EL NIDO DEL CUCO (SERIE FJÄLLBACKA 11)",
        "Autor":"CAMILLA LACKBERG",
        "Genero":["Novela negra"],
        "Descripcion":"Tras cinco años desde La bruja, por fin la esperadísima nueva entrega de la serie de Fjällbacka.Dos sucesos terribles sin una conexión lógica sacuden Fjällbacka. Encuentran a un famoso fotógrafo brutalmente asesinado en una sala de exposiciones, y en la casa del supuesto ganador del premio Nobel de Literatura, en una pequeña isla donde el escritor está ultimando su nuevo libro, sucede una sangrienta tragedia.",
        "Valoracion":0,
        "Resena":[],
    },{
        "Portada":"https://imagessl2.casadellibro.com/a/l/t7/52/9788491293552.jpg",
        "Nombre":"EL CUCO DE CRISTAL",
        "Autor":"JAVIER CASTILLO",
        "Genero":["Novela negra"],
        "Descripcion":"Nueva York, 2017. Cora Merlo, médico residente de primer año, sufre un infarto fulminante que la obliga a un trasplante de corazón. Aún convaleciente la joven recibe la visita de una extraña mujer con una enigmática oferta: pasar unos días en Steelville, un pequeño pueblo de interior, para conocer la vida de su hijo Charles, el donante de su corazón.",
        "Valoracion":0,
        "Resena":[],
    },{
        "Portada":"https://imagessl6.casadellibro.com/a/l/t7/96/9788411073196.jpg",
        "Nombre":"LA TABERNA DE SILOS",
        "Autor":"LORENZO G. ACEBEDO",
        "Genero":["Novela negra"],
        "Descripcion":"Corre la primera mitad del siglo XIII cuando el abad del monasterio de San Millán encarga a uno de sus servidores, Gonzalo de Berceo, la misión de viajar al monasterio de Silos para copiar un manuscrito latino y hacer con el un poema castellano.",
        "Valoracion":0,
        "Resena":[],
    },{
        "Portada":"https://imagessl1.casadellibro.com/a/l/t7/61/9788423363261.jpg",
        "Nombre":"PUA",
        "Autor":"LORENZO SILVA",
        "Genero":["Novela negra"],
        "Descripcion":"El pasado vuelve para sacudir la vida de un antiguo agente secreto cuando ya no tiene el escudo de su organización. Participó en la guerra sucia del Estado, convencido de su causa: la defensa de una sociedad democrática y de las víctimas inocentes contra la violencia terrorista. ",
        "Valoracion":0,
        "Resena":[],
    },{
        "Portada":"https://imagessl2.casadellibro.com/a/l/t7/02/9788467068702.jpg",
        "Nombre":"DELITO",
        "Autor":"CARME CHAPARRO",
        "Genero":["Novela negra"],
        "Descripcion":"El primer ser humano revienta contra el asfalto a las diez y cuarenta y dos minutos de la noche del domingo dos de junio. Un hombre que camina al otro lado de la plaza levanta instintivamente la vista.",
        "Valoracion":0,
        "Resena":[],
    },{
        "Portada":"https://imagessl9.casadellibro.com/a/l/t7/79/9788423362479.jpg",
        "Nombre":"ESPERANDO AL DILUVIO",
        "Autor":"DOLORES REDONDO",
        "Genero":["Novela negra"],
        "Descripcion":"Un salvaje asesino en serie. Una búsqueda hasta el último latido. Una ciudad amenazada por un diluvio. Entre los años 1968 y 1969, el asesino al que la prensa bautizaría como John Biblia mató a tres mujeres en Glasgow. Nunca fue identificado y el caso todavía sigue abierto hoy en día. ",
        "Valoracion":0,
        "Resena":[],
    },{
        "Portada":"https://imagessl0.casadellibro.com/a/l/t7/80/9788466675680.jpg",
        "Nombre":"TODO VUELVE (SERIE TODO ARDE 2)",
        "Autor":"JUAN GOMEZ JURADO",
        "Genero":["Novela negra"],
        "Descripcion":"Tras el éxito de Todo arde llega la esperada continuación de la saga que ha cautivado a la crítica",
        "Valoracion":0,
        "Resena":[],
    },{
        "Portada":"https://imagessl0.casadellibro.com/a/l/t7/60/9788420476360.jpg",
        "Nombre":"EL PROBLEMA FINAL",
        "Autor":"ARTURO PEREZ REVERTE",
        "Genero":["Novela negra"],
        "Descripcion":"No se trata de un desafío entre el asesino y el detective, sino de un duelo de inteligencia entre el autor y el lector.",
        "Valoracion":0,
        "Resena":[],
    },{
        "Portada":"https://imagessl0.casadellibro.com/a/l/t7/30/9788401030130.jpg",
        "Nombre":"LA ARMADURA DE LA LUZ. SAGA LOS PILARES DE LA TIERRA",
        "Autor":"KEN FOLLETT",
        "Genero":["Novela histórica"],
        "Descripcion":"792. Un gobierno tiránico está decidido a convertir Inglaterra en un poderoso imperio comercial. Mientras, Napoleón Bonaparte comienza su ambicioso ascenso al poder y, en medio de un gran descontento social, los vecinos de Francia se mantienen en máxima alerta.",
        "Valoracion":0,
        "Resena":[],
    },{
        "Portada":"https://imagessl5.casadellibro.com/a/l/t7/35/9788467069235.jpg",
        "Nombre":"LAS BRUJAS Y EL INQUISIDOR: PREMIO PRIMAVERA DE NOVELA 2023",
        "Autor":"ELVIRA ROCA BAREA",
        "Genero":["Novela histórica"],
        "Descripcion":"En 1609 varias personas son acusadas de brujería en la aldea navarra de Zugarramurdi. Lo que parecía un episodio puntual, sin importancia, va adquiriendo una virulencia inusitada. En estas circunstancias el inquisidor general Bernardo de Sandoval envía a Alonso de Salazar y Frías a Logroño, sede del Santo Oficio.",
        "Valoracion":0,
        "Resena":[],
    },{
        "Portada":"https://imagessl2.casadellibro.com/a/l/t7/62/9788467067262.jpg",
        "Nombre":"EL OCASO DE ROMA",
        "Autor":"CARLOS DE MIGUEL",
        "Genero":["Novela histórica"],
        "Descripcion":"Finales del siglo III d.C.: Flavio Constancio, joven y prometedor soldado, antes de partir en campaña hacia Palmira, deja a Helena, su joven esposa embarazada, camino de la ciudad de Naissus con la única compañía de una joven esclava.",
        "Valoracion":0,
        "Resena":[],
    },{
        "Portada":"https://imagessl3.casadellibro.com/a/l/t7/23/9788491398523.jpg",
        "Nombre":"LA PRIMERA MESTIZA",
        "Autor":"CARMEN SANCHEZ RISCO",
        "Genero":["Novela histórica"],
        "Descripcion":"Madrid, 1597. Francisca Pizarro Yupanqui, la primera mestiza noble del Perú, heredera de las dos fuerzas imperantes y enfrentadas, una de las mujeres más poderosas y ricas de la época, comienza a redactar de su puño y letra el relato oculto de su larga y azarosa existencia, en una confesión dirigida a quienes deberán juzgar y defender su memoria mestiza.",
        "Valoracion":0,
        "Resena":[],
    },{
        "Portada":"https://imagessl2.casadellibro.com/a/l/t7/82/8432715150282.jpg",
        "Nombre":"LEJOS DE LUISIANA",
        "Autor":"LUZ GABAS",
        "Genero":["Novela histórica"],
        "Descripcion":"Después de años de colonización, la familia Girard acepta la controvertida decisión de su país, Francia, de ceder a España en 1763 parte de las indómitas tierras del Misisipi; sin embargo, sufrirá las consecuencias de las rebeliones de sus compatriotas contra los españoles, la guerra de norteamericanos contra ingleses por la independencia de los Estados Unidos y la lucha desesperada de los nativos indios por la supervivencia de sus pueblos. ",
        "Valoracion":0,
        "Resena":[],
    },{
        "Portada":"https://imagessl7.casadellibro.com/a/l/t7/87/9788466673587.jpg",
        "Nombre":"EL TABLERO DE LA REINA",
        "Autor":"LUIS ZUECO",
        "Genero":["Novela histórica"],
        "Descripcion":"Año 1468. Castilla se encuentra en un momento crucial de su historia. Alfonso de Trastámara ha muerto en sospechosas circunstancias y Enrique IV se alza como rey obligando a su hermanastra Isabel, la única que podría oponerse a sus planes, a firmar la paz.",
        "Valoracion":0,
        "Resena":[],
    },{
        "Portada":"https://imagessl1.casadellibro.com/a/l/t7/71/9788408273271.jpg",
        "Nombre":"GLADIADORAS",
        "Autor":"JUAN TRANCHE",
        "Genero":["Novela histórica"],
        "Descripcion":"Año 131 d. C. El pueblo de Roma celebra el combate de gladiadoras más increíble que jamás se haya visto. Movidas por el anhelo de libertad y la venganza, dos mujeres se enfrentan en un duelo definitivo. El duelo de la eternidad.",
        "Valoracion":0,
        "Resena":[],
    },{
        "Portada":"https://imagessl5.casadellibro.com/a/l/t7/65/9788420461465.jpg",
        "Nombre":"REVOLUCION",
        "Autor":"ARTURO PEREZ REVERTE",
        "Genero":["Novela histórica"],
        "Descripcion":"Ésta es la historia de un hombre, tres mujeres, una revolución y un  tesoro. La revolución fue la de México en tiempos de Emiliano Zapata y  Francisco Villa. El tesoro fueron quince mil monedas de oro de a veinte  pesos de las denominadas maximilianos, robadas en un  banco de Ciudad  Juárez el 8 de mayo de 1911. ",
        "Valoracion":0,
        "Resena":[],
    },{
        "Portada":"https://imagessl4.casadellibro.com/a/l/t7/94/9788435064194.jpg",
        "Nombre":"BREO. EL CELTA QUE DESAFIO A ROMA",
        "Autor":"FRANCISCO NARLA",
        "Genero":["Novela histórica"],
        "Descripcion":"Su padre había iniciado el camino, pero fue traicionado. Él, sin embargo, se refugió en la costa, lejos de los clanes; sólo deseaba embarcar hacia las verdes islas del norte y seguir los pasos de las antiguas leyendas.  Pero su pueblo agonizaba, esclavizado en la mayor mina de oro de la todopoderosa Roma.  ",
        "Valoracion":0,
        "Resena":[],
    },{
        "Portada":"https://imagessl1.casadellibro.com/a/l/t7/81/9788466671781.jpg",
        "Nombre":"ROMA SOY YO",
        "Autor":"SANTIAGO POSTEGUILLO",
        "Genero":["Novela histórica"],
        "Descripcion":"oma, año 77 a.C. El cruel senador Dolabela va a ser juzgado por  corrupción, pero ha contratado a los mejores abogados, ha comprado al  jurado y, además, es conocido por usar la violencia contra todos los que  se enfrentan a él. Nadie se atreve a ser el fiscal, hasta que de pronto,  contra todo pronóstico, un joven patricio de tan solo veintitrés años  acepta llevar la acusación, defender al pueblo de Roma y desafiar el  poder de las élites.",
        "Valoracion":0,
        "Resena":[],
    }
]


mongoose.connect('mongodb+srv://root:root@cluster0.oc2ykpm.mongodb.net/StreamHub?retryWrites=true&w=majority')
.then(async () => {
    const allLibros = await Libro.find()
    if(allLibros.length > 0){
        await Libro.collection.drop()
        console.log('Libros borrados')
    }
})
.catch(err => console.error('Error borrando',err))
.then(async() => {
    const librosMap = arrayLibros.map((libro) => new Libro(libro))
    await Libro.insertMany(librosMap)
    console.log('Libros añadidos');
})
.catch(err => console.error('Error insertando',err))
.finally(() => mongoose.disconnect());