const Pelicula = require ('../api/models/pelicula.model')
const mongoose = require('mongoose');

const arrayPeliculas = [
    {
    "Portada":"https://www.taquillaespana.es/wp-content/uploads/2021/04/2020-Guardianes-de-la-noche.-Tren-infinito-Kimetsu-no-Yaiba.-Mugen-Ressha-Hen-tt11032374-Espanol-02-800x445.jpeg",
    "Nombre":"Guardianes de la noche -Kimetsu no Yaiba- La Película: Tren Infinito",
    "Trailer":"https://www.youtube.com/watch?v=ehyYlwBj-So",
    "Duracion": 116,
    "Fecha": 2021,
    "Genero":["Anime"],
    "Descripcion":"Tras completar el entrenamiento en la Mansión de la Mariposa, Tanjiro y sus compañeros se dirigen a su siguiente misión, el Tren del Infinito, donde más de 40 personas han desaparecido en un periodo muy corto de tiempo. Tanjiro y Nezuko, acompañados por Zenitsu e Inosuke, se unen a uno de los espadachines más poderosos entre los miembros del Cuerpo de Matademonios.",
    "Valoracion":0,
    "Resena":[],
    },
    {
    "Portada":"https://ramenparados.com/wp-content/uploads/2020/05/My-Hero-Academia-Two-Heroes-destacado-e1588690096118.jpg",
    "Nombre":"My Hero Academia: Dos héroes",
    "Trailer":"https://www.youtube.com/watch?v=hk5ZLDFAFsc",
    "Duracion": 95,
    "Fecha": 2018,
    "Genero":["Anime"],
    "Descripcion":"Mientras los alumnos de la Escuela UA se preparan para asistir a un campamento de verano, Izuku y All Might reciben una invitación para visitar la ciudad móvil conocida como “1-Island” que flota sobre el mar. Durante la “I Expo” en la que se muestran los resultados de las investigaciones de los científicos de todo el mundo que estudian los dones, Izuku conoce a la joven Melissa.",
    "Valoracion":0,
    "Resena":[],
    },
    {
    "Portada":"https://pics.filmaffinity.com/Buda_2_Camino_a_la_Iluminaciaon-833379731-large.jpg",
    "Nombre":"Buda 2: Camino a la Iluminación",
    "Trailer":"https://www.youtube.com/watch?v=nL-6ouEdHWY",
    "Duracion": 85,
    "Fecha": 2014,
    "Genero":["Anime"],
    "Descripcion":"Hace 2500 años, Siddhartha nació en el Reino de Shakya, pero renuncia a su posición como Príncipe heredero para poder descubrir el mundo por sí mismo. En esta nueva etapa de su viaje hacia la iluminación conocerá a nuevos compañeros. Siddhartha no es consciente que mientras él continúa su viaje, el Reino de Kosala se prepara para llevar a cabo el ataque definitivo contra Shakya",
    "Valoracion":0,
    "Resena":[],
    },
    {
    "Portada":"https://www.lavanguardia.com/peliculas-series/images/movie/backdrop/2015/8/w1280/8kQtBcax6zqiwFhDRS2mmPvLf8.jpg",
    "Nombre":"Boruto: Naruto, La Película",
    "Trailer":"https://www.youtube.com/watch?v=tzcF1d4C_G8",
    "Duracion": 95,
    "Fecha": 2015,
    "Genero":["Anime"],
    "Descripcion":"Con Naruto como Séptimo Hokage, la Villa de la Hoja tiene previsto ser la sede de los exámenes de Chuunin para entrenar a los nuevos ninjas tanto de la Hoja como de las demás villas aliadas.",
    "Valoracion":0,
    "Resena":[],
    },
    {
    "Portada":"https://sm.ign.com/ign_es/image/d/dragon-bal/dragon-ball-super-broly-north-american-theatrical-opening-da_xdf1.jpg",
    "Nombre":"Dragon Ball Super: Broly",
    "Trailer":"https://www.youtube.com/watch?v=SQ53hHKu0hI",
    "Duracion": 0,
    "Fecha": 123,
    "Genero":["Anime"],
    "Descripcion":"La paz ha regresado una vez más a la Tierra después del Torneo de Poder. Tras descubrir que en los diferentes universos hay seres increíblemente poderosos que aún no ha visto, Goku tiene intención de seguir entrenando para hacerse aún más fuerte. Entonces, un día, un saiyan llamado Broly al que nunca antes han visto se presenta ante Goku y Vegeta.",
    "Valoracion":0,
    "Resena":[],
    },
    {
    "Portada":"https://imagenes.20minutos.es/files/og_thumbnail/uploads/imagenes/2019/11/11/one-piece-estampida.jpg",
    "Nombre":"One Piece: Estampida",
    "Trailer":"https://www.youtube.com/watch?v=HLyXCOgXJns",
    "Duracion": 101,
    "Fecha": 2019,
    "Genero":["Anime"],
    "Descripcion":"La mayor feria del mundo de los piratas realizada por piratas para piratas: el Festival de los Piratas. Luffy y el resto de la tripulación de Sombreros de Paja reciben la invitación de su anfitrión Buena Festa, conocido como el Maestro de las Festividades. Cuando llegan, encuentran un lugar atestado de pabellones glamurosos y muchos piratas incluidos los de la peor generación.",
    "Valoracion":0,
    "Resena":[],
    },
    {
    "Portada":"https://i.blogs.es/39ea87/cartel-dragon-ball-la-resurreccion-de-f/1366_2000.jpg",
    "Nombre":"Dragon Ball Z: La resurección de F",
    "Trailer":"https://www.youtube.com/watch?v=cD8Vv5bdmbI",
    "Duracion": 94,
    "Fecha": 2015,
    "Genero":["Anime"],
    "Descripcion":"Sorbet y Tagoma, dos supervivientes del ejército del Emperador Freeza llegan a la Tierra con la intención de usar las bolas de dragón para resucitar al tirano espacial y restaurar su imperio. Meses más tarde, es el mismísimo Freeza el que viaja a la Tierra al frente de un numeroso ejército con un único objetivo en mente: vengarse de Son Goku.",
    "Valoracion":0,
    "Resena":[],
    },
    {
    "Portada":"https://images-na.ssl-images-amazon.com/images/S/pv-target-images/10867c49ba9c6dc79a01bedd6fa1b1c4ca3c87a929f674c17b121102e03fd471._RI_TTW_SX720_FMjpg_.jpg",
    "Nombre":"Mutafukaz",
    "Trailer":"https://www.youtube.com/watch?v=yB9zhJcvgyg",
    "Duracion": 90,
    "Fecha": 2018,
    "Genero":["Anime"],
    "Descripcion":"Angelino es un pobre diablo que malvive en Dark Meat City, una mega-urbe infestada de bandas violentas, policías corruptos y buscavidas sin escrúpulos. Mientras trabaja como repartidor tiene un accidente al distraerse con una misteriosa chica y eso cambiará por completo su vida, ya que a partir de entonces empezará a tener terribles visiones de seres monstruosos que acechan por toda la ciudad.",
    "Valoracion":0,
    "Resena":[],
    },
    {
    "Portada":"https://podcastonepiece.files.wordpress.com/2016/12/op-gold-1.jpg",
    "Nombre":"One Piece Gold",
    "Trailer":"https://www.youtube.com/watch?v=z0LNGN5GHtU",
    "Duracion": 120,
    "Fecha": 2016,
    "Genero":["Anime"],
    "Descripcion":"Luffy y el resto de Piratas de Sombrero de Paja deciden poner rumbo a una embarcación dorada de 10 kilómetros tan grande como una ciudad, un lugar reconocido como país independiente por el Gobierno Mundial, la mayor ciudad del entretenimiento del mundo: Gran Tesoro.",
    "Valoracion":0,
    "Resena":[],
    },
    {
    "Portada":"https://static.filmin.es/images/media/11758/1/still_0_3_1920x1080.webp",
    "Nombre":"La chica satélite y el chico vaca",
    "Trailer":"https://www.youtube.com/watch?v=ELFPnOfpUHw",
    "Duracion": 77,
    "Fecha": 2014,
    "Genero":["Anime"],
    "Descripcion":"Ilo es un satélite que observa la Tierra desde el espacio, curiosa por el funcionamiento del corazón humano. Joon es un aspirante a músico que tiene el corazón roto tras ser abandonado por su novia, y por ello termina convertido en una vaca lechera. En ese momento es cuando aparece el malvado Incinerador, dispuesto a robar los órganos de aquellas personas con el corazón roto.",
    "Valoracion":0,
    "Resena":[],
    },
    {
    "Portada":"https://ntvb.tmsimg.com/assets/p7764_v_h8_am.jpg?w=960&h=540",
    "Nombre":"The Terminator",
    "Trailer":"https://www.youtube.com/watch?v=9sB0R7kArD8",
    "Duracion": 107,
    "Fecha": 1985,
    "Genero":["Accion"],
    "Descripcion":"Un ser cibernético casi indestructible (Arnold Schwarzenegger) es enviado desde el futuro para asesinar a una mujer (Linda Hamilton).",
    "Valoracion":0,
    "Resena":[],
    },
    {
    "Portada":"https://i.blogs.es/9648bb/05043c25fb559f4f80de86045f8b92352b134ca7/1366_2000.jpg",
    "Nombre":"Venom",
    "Trailer":"https://www.youtube.com/results?search_query=venom+trailer+espa%C3%B1ol",
    "Duracion": 108,
    "Fecha": 2018,
    "Genero":["Accion", "Drama"],
    "Descripcion":"VENOM, uno de los personajes más enigmáticos y populares de Marvel protagoniza esta nueva aventura. Eddie Brock (Tom Hardy) lleva tiempo intentando desenmascarar al famoso científico Carlton Drake (Riz Ahmed), una obsesión que ha arruinado su carrera de periodista y su relación con su novia, Anne (Michelle Williams). Al investigar uno de los experimentos de Drake, el ente alienígena Venom se...",
    "Valoracion":0,
    "Resena":[],
    },
    {
    "Portada":"https://i.blogs.es/0013bc/rampage-chinese-poster-with-dwayne-johnson/1366_2000.jpg",
    "Nombre":"Proyecto Rampage",
    "Trailer":"https://www.youtube.com/watch?v=-vtvnuKjXrI",
    "Duracion": 107,
    "Fecha": 2018,
    "Genero":["Accion", "Fantasia"],
    "Descripcion":"Cuando un experimento genético falla, desata supercriaturas que arrasan la ciudad. El científico Davis se lanza para conseguir un antídoto e intenter salvar al simio que fue su amigo.",
    "Valoracion":0,
    "Resena":[],
    },
    {
    "Portada":"https://www.lavanguardia.com/peliculas-series/images/movie/backdrop/2022/8/w1280/jHKNqz0LjM2dOUv5XDPmcSoYPEW.jpg",
    "Nombre":"Maneater",
    "Trailer":"https://www.youtube.com/watch?v=ygOStSK84cY",
    "Duracion": 83,
    "Fecha": 2022,
    "Genero":["Accion", "Terror"],
    "Descripcion":"Un grupo de amigos viajan a las Bahamas para pasar un fin de semana de sol y aventura cuando se quedan atrapados y un letal tiburón les ataca. Su única posibilidad de salir de allí con vida será acabar con el tiburón antes de que él acabe con ellos. Pero contarán con la ayuda de Harlan, un pescador que tiene cuentas pendientes con el feroz animal, responsable de la muerte de su hija.",
    "Valoracion":0,
    "Resena":[],
    },
    {
    "Portada":"https://cdn.autobild.es/sites/navi.axelspringer.es/public/media/image/2020/02/fast-furious-9-1857267.jpg",
    "Nombre":"Fast & Furious 9",
    "Trailer":"https://www.youtube.com/results?search_query=fast+%26+furious+9+trailer+espa%C3%B1ol",
    "Duracion": 144,
    "Fecha": 2021,
    "Genero":["Accion"],
    "Descripcion":"En este noveno capítulo de la saga, la amenaza obligará a Dom Toretto a enfrentarse a los pecados de su pasado si quiere salvar a aquellos que más quiere. El equipo se vuelve a reunir para impedir un complot a escala mundial, liderado por uno de los asesinos más peligrosos y mejor conductor a los que se han enfrentado; un hombre que además es el hermano desaparecido de Dom, Jakob.",
    "Valoracion":0,
    "Resena":[],
    },
    {
    "Portada":"https://as02.epimg.net/meristation/imagenes/2021/05/12/videos/1620835148_943994_1620835235_noticia_normal.jpg",
    "Nombre":"La Purga: Infinita",
    "Trailer":"https://www.youtube.com/watch?v=RlJqJUnjhZw",
    "Duracion": 103,
    "Fecha": 2021,
    "Genero":["Accion", "Terror"],
    "Descripcion":"UNA NOCHE NO ES SUFICIENTE, los miembros de un movimiento clandestino, insatisfechos con la noche anual de anarquía y asesinatos, deciden apoderarse del país mediante una campaña infinita de caos y masacre. La mañana siguiente a La Purga, una banda de asesinos enmascarados ataca a una rica familia de ganaderos de Texas y a sus trabajadores.",
    "Valoracion":0,
    "Resena":[],
    },
    {
    "Portada":"https://i.blogs.es/0938ae/bg/1366_2000.jpeg",
    "Nombre":"Operación Fortune: El Gran Engaño",
    "Trailer":"https://www.youtube.com/watch?v=xSo-W-0kgYQ",
    "Duracion": 114,
    "Fecha": 2023,
    "Genero":["Accion", "Comedia"],
    "Descripcion":"El agente del MI6 Orson Fortune (Jason Statham) y su equipo reclutan a una de las estrellas de cine más importantes de Hollywood (Josh Harnett), para que los ayude en una misión encubierta para rastrear y detener la venta de nuevas tecnologías de armas mortales, a manos del multimillonario Greg Simmonds (Hugh Grant).",
    "Valoracion":0,
    "Resena":[],
    },
    {
    "Portada":"https://i.blogs.es/b58302/creed2/1366_2000.jpg",
    "Nombre":"Creed II",
    "Trailer":"https://www.youtube.com/watch?v=klYuSuUCiJI",
    "Duracion": 129,
    "Fecha": 2019,
    "Genero":["Accion", "Drama"],
    "Descripcion":"El siguiente capítulo de la historia de Adonis Creed sigue su vida dentro y fuera del ring mientras trata con su nueva encontrada fama, los problemas con su familia y su continua búsqueda para convertirse en un campeón.",
    "Valoracion":0,
    "Resena":[],
    },
    {
    "Portada":"https://cdn.hobbyconsolas.com/sites/navi.axelspringer.es/public/media/image/2023/01/boda-explosiva-2939078.jpg?tf=3840x",
    "Nombre":"Una boda explosiva",
    "Trailer":"https://www.youtube.com/watch?v=r5q3YC9RiXY",
    "Duracion": 101,
    "Fecha": 2023,
    "Genero":["Accion", "Comedia", "Romance"],
    "Descripcion":"Darcy (Jennifer Lopez) y Tom (Josh Duhamel) viajan con sus familias para celebrar su boda, pero cuando todos los invitados son tomados como rehenes, la frase «hasta que la muerte nos separe» adquiere un nuevo significado en esta desternillante aventura cargada de adrenalina en la que Darcy y Tom tendrán que salvar a sus seres queridos, si no se matan entre ellos antes.",
    "Valoracion":0,
    "Resena":[],
    },
    {
    "Portada":"https://cdn.hobbyconsolas.com/sites/navi.axelspringer.es/public/media/image/2021/10/john-wick-4-2493995.jpg?tf=3840x",
    "Nombre":"Jonh Wick 4",
    "Trailer":"https://www.youtube.com/watch?v=L0anWmmd8TI",
    "Duracion": 162,
    "Fecha": 2023,
    "Genero":["Accion"],
    "Descripcion":"John Wick (Keanu Reeves) descubre un camino para derrotar a la Alta Mesa. Pero para poder ganar su libertad, Wick deberá enfrentarse a un nuevo rival con poderosas alianzas en todo el mundo, capaz de convertir a viejos amigos en enemigos.",
    "Valoracion":0,
    "Resena":[],
    },
    {
    "Portada":"https://cdn.hobbyconsolas.com/sites/navi.axelspringer.es/public/media/image/2021/02/rey-zamunda-2218311.jpeg",
    "Nombre":"El rey de Zamunda",
    "Trailer":"https://www.youtube.com/watch?v=GHt8xzq1YTo",
    "Duracion": 109,
    "Fecha": 2021,
    "Genero":["Comedia", "Romance"],
    "Descripcion":"¡Akeem y Senmi han vuelto! Desde el exuberante reino de Zamunda, el recién coronado rey Akeem (Eddie Murphy) y su leal confidente Semmi (Arsenio Hall) emprenden una nueva y divertidísima aventura que les hará atravesar el mundo, desde su gran país en África hasta el barrio de Queens, en Nueva York, donde todo empezó.",
    "Valoracion":0,
    "Resena":[],
    },
    {
    "Portada":"https://estaticos-cdn.elperiodico.com/clip/284011d2-7628-4c44-aaf3-2932f9ad635d_alta-libre-aspect-ratio_default_0.jpg",
    "Nombre":"En guerra con mi abuelo",
    "Trailer":"https://www.youtube.com/watch?v=KfjEumnQroM",
    "Duracion": 98,
    "Fecha": 2020,
    "Genero":["Comedia", "Dama"],
    "Descripcion":"El joven Peter se ve obligado a abandonar su habitación cuando su abuelo Ed (Robert De Niro) recientemente enviudado se muda a su casa. Con la ayuda de sus amigos, Peter declara la guerra a su abuelo para hacerle abandonar la habitación, pero Ed es un testarudo y no va a ponérselo nada fácil.",
    "Valoracion":0,
    "Resena":[],
    },
    {
    "Portada":"https://www.formulatv.com/images/articulos/116000/116931_R2UHqYE0cBNPtx384a96oRs5WJi1eLzv7-h2.jpg",
    "Nombre":"Astérix y Obélix contra César",
    "Trailer":"https://www.youtube.com/watch?v=oRj67CNFFg4",
    "Duracion": 110,
    "Fecha": 2000,
    "Genero":["Comedia", "Fantasia"],
    "Descripcion":"El malvado romano Detritus intenta hacerse con la fórmula de la poción que hace invencibles a los galos. Una gran aventura llena de humor, miles de extras y efectos especiales.",
    "Valoracion":0,
    "Resena":[],
    },
    {
    "Portada":"https://pics.filmaffinity.com/Un_novio_para_mi_mujer-120019553-large.jpg",
    "Nombre":"Un novio para mi mujer",
    "Trailer":"https://www.youtube.com/watch?v=yU_ms32GeRw",
    "Duracion": 92,
    "Fecha": 2022,
    "Genero":["Comedia", "Romance"],
    "Descripcion":"Diego quiere separarse de su mujer, Lucía, pero no sabe cómo decírselo. Incapaz de decírselo a la cara, recurre al Cuervo Flores, un afamado seductor «de los de antes», que intentará enamorar a Lucía para que sea ella quien termine con su matrimonio.",
    "Valoracion":0,
    "Resena":[],
    },
    {
    "Portada":"https://hips.hearstapps.com/hmg-prod/images/93-frases-de-chicas-malas-para-enfrentarse-a-la-vida-1643197566.jpg",
    "Nombre":"Chicas malas",
    "Trailer":"https://www.youtube.com/watch?v=zqeoAJp2MRs",
    "Duracion": 99,
    "Fecha": 2004,
    "Genero":["Comedia"],
    "Descripcion":"Cady cree entender lo de 'la supervivencia del más apto', pero la ley del más fuerte cobra un nuevo significado cuando la joven de 15 años educada en casa va al instituto por primera vez.",
    "Valoracion":0,
    "Resena":[],
    },
    {
    "Portada":"https://i0.wp.com/www.audiovisual451.com/wp-content/uploads/2021/05/GarciayGarcia_FotoGrupo_Logo.jpg?fit=1920%2C1357&ssl=1",
    "Nombre":"Garcia y Garcia",
    "Trailer":"https://www.youtube.com/watch?v=h_qaqdkaS0Y",
    "Duracion": 98,
    "Fecha": 2021,
    "Genero":["Comedia"],
    "Descripcion":"Dos Javier García son confundidos e intercambian sus papeles: Javier García, mecánico en paro, debe diseñar una estrategia de empresa low cost, y Javier García, asesor internacional, arreglarles un avión. Aambos se van enfrentando a los cometidos del otro, hasta que una fiesta en una loca persecución por las pistas del aeropuerto deciden en el último momento sus destinos",
    "Valoracion":0,
    "Resena":[],
    },
    {
    "Portada":"https://i.blogs.es/06b257/la-ciudad-perdida-cartel/1366_2000.jpeg",
    "Nombre":"La Ciudad Perdida",
    "Trailer":"https://www.youtube.com/watch?v=VPOLHCJkLw0",
    "Duracion": 111,
    "Fecha": 2022,
    "Genero":["Comedia", "Accion"],
    "Descripcion":"Cuando los secuestran para encontrar una ciudad perdida, Loretta, una escritora, y Alan, el modelo de portada, emprenden un emocionante viaje. La pareja deberá encontrar el fabuloso tesoro de la ciudad perdida antes de que se pierda para siempre.",
    "Valoracion":0,
    "Resena":[],
    },
    {
    "Portada":"https://i.blogs.es/1a2058/cartel-aves-presa/1366_2000.jpeg",
    "Nombre":"Aves de presa",
    "Trailer":"https://www.youtube.com/watch?v=FMfV147maQI",
    "Duracion": 108,
    "Fecha": 2020,
    "Genero":["Comedia", "Accion"],
    "Descripcion":"Cuando uno de los villanos más malvados de Gotham, Roman Sionis, pone su objetivo en una niña llamada Cass, Harley se une a Cazadora, Canario Negro y Renée Montoya para acabar con él.",
    "Valoracion":0,
    "Resena":[],
    },
    {
    "Portada":"https://i.blogs.es/4a666c/padre-no-hay-mas-que-uno-tres/1366_2000.jpeg",
    "Nombre":"Padre no hay mas que uno 3",
    "Trailer":"https://www.youtube.com/watch?v=Rn3FuSYL25o",
    "Duracion": 98,
    "Fecha": 2022,
    "Genero":["Comedia"],
    "Descripcion":"Se acercan las Navidades y la familia de “Padre no hay más que uno” se enfrenta a nuevas y divertidas peripecias. Los niños rompen accidentalmente una figurilla del Belén de colección de su padre y deben conseguir por todos los medios una igual, el problema es que es una pieza única de anticuario.",
    "Valoracion":0,
    "Resena":[],
    },
    {
    "Portada":"https://i.blogs.es/c15087/a-todo-tren-destino-asturias-cartel/1366_2000.jpeg",
    "Nombre":"¡A todo tren! Destino Asturias",
    "Trailer":"https://www.youtube.com/watch?v=8wM-hJOyPtk",
    "Duracion": 88,
    "Fecha": 2021,
    "Genero":["Comedia"],
    "Descripcion":"Cuando Ricardo, padre responsable volcado en su hijo, decide llevarle a un campamento en Asturias en tren nocturno, algunos de los padres proponen que sea él quien lleve a varios de sus hijos. Sin embargo, no cuentan que en el último minuto le acompañe Felipe, un abuelo de dos de los niños, un tipo extravagante e irresponsable. Nada puede salir mal...",
    "Valoracion":0,
    "Resena":[],
    },
    {
    "Portada":"https://www.panoramaaudiovisual.com/wp-content/uploads/2014/07/Como-entrenar-a-tu-dragon-2-web.jpg",
    "Nombre":"Cómo entrenar a tu dragón 2",
    "Trailer":"https://www.youtube.com/watch?v=ZBWOEjInUYs",
    "Duracion": 101,
    "Fecha": 2014,
    "Genero":["Fantasia", "Comedia"],
    "Descripcion":"El segundo capítulo nos devuelve al fantástico mundo de Hipo y Desdentao cinco años después. En una de sus aventuras encontrarán una caverna de hielo con cientos de dragones.",
    "Valoracion":0,
    "Resena":[],
    },
    {
    "Portada":"https://i0.wp.com/imgs.hipertextual.com/wp-content/uploads/2016/03/kung-fu-panda-portada2.jpg?fit=1920%2C1080&quality=50&strip=all&ssl=1",
    "Nombre":"Kung Fu Panda 3",
    "Trailer":"https://www.youtube.com/watch?v=J9B2OpFOnrg",
    "Duracion": 94,
    "Fecha": 2016,
    "Genero":["Fantasia", "Comedia"],
    "Descripcion":"El perdido durante mucho tiempo padre de Po aparece de repente y juntos viajan a un paraíso secreto de osos pandas. Cuando el villano sobrenatural Kai comienza a recorrer toda China venciendo a todos los maestros de kung fu, Po deberá hacer lo imposible: aprender a entrenar a una comunidad repleta de divertidos y torpes hermanos para formar el equipo definitivo de Kung Fu Pandas.",
    "Valoracion":0,
    "Resena":[],
    },
    {
    "Portada":"https://media.revistagq.com/photos/5ca5f4853492a9805bbf10af/master/pass/parque_jurasico_9973.jpg",
    "Nombre":"Parque Jurásico",
    "Trailer":"https://www.youtube.com/watch?v=OsaphlwhhmY",
    "Duracion": 127,
    "Fecha": 1993,
    "Genero":["Fantasia"],
    "Descripcion":"El multimillonario John Hammond consigue hacer realidad su sueño de clonar dinosaurios del Jurásico y crear con ellos un parque temático en una isla remota.",
    "Valoracion":0,
    "Resena":[],
    },
    {
    "Portada":"https://sm.ign.com/ign_es/screenshot/default/nuevo-poster-sonic-2-la-pelicula_s5e6.jpg",
    "Nombre":"Sonic 2: La Película",
    "Trailer":"https://www.youtube.com/watch?v=Mw64Q2bUCGo",
    "Duracion": 122,
    "Fecha": 2022,
    "Genero":["Fantasia", "Accion"],
    "Descripcion":"¡El puercoespín azul preferido del mundo ha vuelto! El doctor Robotnik regresa y, con la ayuda de Knuckles, quiere encontrar una poderosa esmeralda. Sonic y su nuevo socio, Tails, intentan frustrar los planes del doctor Robotnik.",
    "Valoracion":0,
    "Resena":[],
    },
    {
    "Portada":"https://3.bp.blogspot.com/-t8O9XgcL2ZE/Vzv2KjVDxLI/AAAAAAAA_s4/zobJFHx5Z80xjYDwAnqerr-JcjkJ2KdmgCLcB/s1600/wallpaper-elencantodelabestia-1.jpg",
    "Nombre":"El encanto de la bestia",
    "Trailer":"https://www.youtube.com/watch?v=nxGtPfSM_YA",
    "Duracion": 86,
    "Fecha": 2011,
    "Genero":["Fantasia", "Drama", "Romance"],
    "Descripcion":"Vanessa Hudgens protagoniza esta versión moderna del clásico en la que un estudiante superficial es transformado en un ser horrible por una compañera de clase y debe encontrar a alguien que le ame tal y como es o seguir 'bestial' para siempre.",
    "Valoracion":0,
    "Resena":[],
    },
    {
    "Portada":"https://frasesdelapelicula.com/wp-content/uploads/2011/11/crepusculo-luna-nueva.jpg",
    "Nombre":"Luna Nueva",
    "Trailer":"https://www.youtube.com/watch?v=sSp81po4DUo",
    "Duracion": 130,
    "Fecha": 2009,
    "Genero":["Fantasia", "Drama"],
    "Descripcion":"Bella y Edward han logrado seguir adelante con su peculiar relación, pero un incidente aislado, que en circunstancias normales no hubiera traído consigo mayores consecuencias, desencadena una serie de eventos que amenaza la vida de la protagonista. El distanciamiento entre ambos hará que Bella retome la amistad con el enigmático Jacob Black, quien al igual que Edward, esconde un secreto ancestral.",
    "Valoracion":0,
    "Resena":[],
    },
    {
    "Portada":"https://images.mubicdn.net/images/film/8789/cache-11429-1628506207/image-w1280.jpg?size=800x",
    "Nombre":"Shrek 2",
    "Trailer":"https://www.youtube.com/watch?v=xBxVgh-kgAI",
    "Duracion": 92,
    "Fecha": 2004,
    "Genero":["Fantasia"],
    "Descripcion":"El héroe favorito vuelve en Shrek 2. El viaje para conocer a los suegros se convierte para Shrek y Fiona en un torbellino de aventuras en el que la version del 'y fueron felices y comieron perdices' nunca estuvo tan lejano… Con la ayuda Asno, Shrek se enfrenta a un Hada Madrina, al pomposo Príncipe Encantador y al famoso Gato con Botas, un fiero felino que no es más que un lindo minino.",
    "Valoracion":0,
    "Resena":[],
    },
    {
    "Portada":"https://www.lavanguardia.com/peliculas-series/images/movie/backdrop/2012/11/w1280/xyXmtuvsoM5J3yNad0nvcetpBdY.jpg",
    "Nombre":"El Hobbit: Un viaje inesperado",
    "Trailer":"https://www.youtube.com/watch?v=sI8OQRXhcZE",
    "Duracion": 169,
    "Fecha": 2012,
    "Genero":["Fantasia"],
    "Descripcion":"La aventura sigue para Bilbo Bolsón y los enanos en su intento de recuperar el reino de Erebor.",
    "Valoracion":0,
    "Resena":[],
    },
    {
    "Portada":"https://socioespectacular.com.uy/wp-content/uploads/2021/11/anilloscomunidad.jpg",
    "Nombre":"El señor de los anillos: La comunidad del anillo",
    "Trailer":"https://www.youtube.com/watch?v=3GJp6p_mgPo",
    "Duracion": 178,
    "Fecha": 2001,
    "Genero":["Fantasia", "Accion"],
    "Descripcion":"En la primera parte, The Lord of the Rings, un joven y tímido hobbit hereda un anillo de oro que guarda el secreto de la supervivencia -o la esclavitud- del mundo entero.",
    "Valoracion":0,
    "Resena":[],
    },
    {
    "Portada":"https://i.blogs.es/61e3eb/samaritan-cartel-amazon-stallone/1366_2000.jpeg",
    "Nombre":"Samaritan",
    "Trailer":"https://www.youtube.com/watch?v=ZmCrptWNGfM",
    "Duracion": 102,
    "Fecha": 2022,
    "Genero":["Fantasia", "Drama", "Accion"],
    "Descripcion":"Sam Clearly, de trece años (Javon 'Wanna' Walton) sospecha que su misterioso y esquivo vecino, el Sr. Smith (Sylvester Stallone) es el legendario héroe samaritan que fue declarado muerto hace 25 años. Con una tasa de criminalidad en aumento y la ciudad al borde del caos, Sam se propone sacar a su vecino de su escondite para que salve la ciudad de la ruina.",
    "Valoracion":0,
    "Resena":[],
    },
    {
    "Portada":"https://cdn.hobbyconsolas.com/sites/navi.axelspringer.es/public/media/image/2023/02/hijo-2969982.jpg?tf=3840x",
    "Nombre":"El hijo",
    "Trailer":"https://www.youtube.com/watch?v=FZFFAMkYw_M",
    "Duracion":122,
    "Fecha":2023,
    "Genero":["Drama"],
    "Descripcion":"La ajetreada vida de Peter (Hugh Jackman) con su nueva pareja Beth (Vanessa Kirby) y su bebé, se desbarata cuando su exmujer, Kate (Laura Dern), aparece con su problemático y distante hijo adolescente, Nicholas, poniendo a la familia en una situación peligrosa, cambiando el curso de sus vidas para siempre.",
    "Valoracion":0,
    "Resena":[],
    },
    {
    "Portada":"https://cinefilosoficial.com/wp-content/uploads/2019/07/orgullo_y_prejuicio.jpg",
    "Nombre":"Orgullo y prejuicio",
    "Trailer":"https://www.youtube.com/watch?v=Ov0PdD5c7m0",
    "Duracion":126,
    "Fecha":2006,
    "Genero":["Drama","Romance"],
    "Descripcion":"El amor surge cuando la enérgica Elizabeth Bennet conoce al soltero, rico y orgulloso Sr. Darcy. ¿Podrá cada uno superar su propio orgullo y sus prejuicios?",
    "Valoracion":0,
    "Resena":[],
    },
    {
    "Portada":"https://e00-elmundo.uecdn.es/assets/multimedia/imagenes/2017/02/23/14878455050932.jpg",
    "Nombre":"La ciudad de las estrellas - La La Land",
    "Trailer":"https://www.youtube.com/watch?v=IHbHn5SLhZo",
    "Duracion":128,
    "Fecha":2017,
    "Genero":["Drama","Comedia"],
    "Descripcion":"La La Land es mucho más que la película más aclamada del año: es un tesoro cinematográfico que perdurará en el tiempo y con el que te enamorarás una y otra vez. Emma Stone y Ryan Gosling son Mia y Sebastian, una actriz y un músicode jazz que persiguen su sueño “made in Hollywood”, y quese encuentran el uno al otro en esta vibrante celebración de la esperanza, los sueños y el amor.",
    "Valoracion":0,
    "Resena":[],
    },
    {
    "Portada":"https://pics.filmaffinity.com/Soy_leyenda-403372181-large.jpg",
    "Nombre":"Soy leyenda",
    "Trailer":"https://www.youtube.com/watch?v=F53gHFtGSwQ",
    "Duracion":100,
    "Fecha":2007,
    "Genero":["Drama","Acción"],
    "Descripcion":"Will Smith interpreta ese único superviviente en Soy Leyenda, una historia épica que fusiona una acción trepidante con la impactante visión de un desolado Manhattan.",
    "Valoracion":0,
    "Resena":[],
    },
    {
    "Portada":"https://i0.wp.com/imgs.hipertextual.com/wp-content/uploads/2018/09/campeones_javier_fesser.jpg?fit=1000%2C667&quality=50&strip=all&ssl=1",
    "Nombre":"Campeones",
    "Trailer":"https://www.youtube.com/watch?v=a3e0hWT09YY",
    "Duracion":119,
    "Fecha":2018,
    "Genero":["Drama","Comedia"],
    "Descripcion":"Marco, un entrenador profesional de baloncesto, se encuentra un día, en medio de una crisis personal, entrenando a un equipo compuesto por personas con discapacidad intelectual. Lo que comienza como un problema se acaba convirtiendo en una lección de vida.",
    "Valoracion":0,
    "Resena":[],
    },
    {
    "Portada":"https://i.blogs.es/1892cf/bones-and-all/1366_2000.jpeg",
    "Nombre":"Hasta los huesos",
    "Trailer":"https://www.youtube.com/watch?v=zz4GL4VyU4g",
    "Duracion":131,
    "Fecha":2022,
    "Genero":["Drama","Terror"],
    "Descripcion":"En un mundo que no los acepta, una joven que está aprendiendo a sobrevivir al margen de la sociedad y un vagabundo empedernido emprenden un viaje por carretera para encontrar su identidad y buscar la belleza en un mundo lleno de peligros.",
    "Valoracion":0,
    "Resena":[],
    },
    {
    "Portada":"https://www.hollywoodreporter.com/wp-content/uploads/2014/11/TIG_200_IG_03812R.jpg?w=3000",
    "Nombre":"The Imitation Game (Descifrando el enigma)",
    "Trailer":"https://www.youtube.com/watch?v=zXKHGaRxQaE",
    "Duracion":114,
    "Fecha":2015,
    "Genero":["Drama"],
    "Descripcion":"Biopic sobre el matemático británico Alan Turing, famoso por haber descifrado los códigos secretos nazis, determinando el devenir de la II Guerra Mundial en favor de los Aliados.",
    "Valoracion":0,
    "Resena":[],
    },
    {
    "Portada":"https://cdn-3.expansion.mx/dims4/default/5c7b8d6/2147483647/strip/true/crop/1500x1500+0+0/resize/1200x1200!/quality/90/?url=https%3A%2F%2Fcdn-3.expansion.mx%2F8e%2F09%2F57f800d24f2b98e5a1386de4170e%2Fnotebook.jpg",
    "Nombre":"Diario de una pasión",
    "Trailer":"https://www.youtube.com/watch?v=QoC8q9Oc2w8",
    "Duracion":123,
    "Fecha":2004,
    "Genero":["Drama","Romance"],
    "Descripcion":"En esta historia de reencuentro de un amor perdido, dos personas comunes y corrientes se vuelven extraordinarias por la fuerza, el poder y la belleza del amor verdadero.",
    "Valoracion":0,
    "Resena":[],
    },
    {
    "Portada":"https://i.blogs.es/1a7f93/el-club-de-la-lucha/840_560.jpeg",
    "Nombre":"El club de la lucha",
    "Trailer":"https://www.youtube.com/watch?v=r5KDiUNZv4w",
    "Duracion": 139,
    "Fecha": 1999,
    "Genero":["Drama"],
    "Descripcion":"Jack (E Norton) es un personaje insomne y desesperado por escapar de su fatal y aburrida vida. En un viaje en avión conoce a Tyler Durden (B Pitt), un carismático vendedor de jabón con una filosofía muy particular; Tyler cree que el perfeccionismo es para los débiles y que es la destrucción de uno mismo lo que realmente hace que la vida merezca la pena.",
    "Valoracion":0,
    "Resena":[],
    },
    {
    "Portada":"https://hips.hearstapps.com/hmg-prod/images/intocable-pelicula-1610538697.jpg",
    "Nombre":"Intocable",
    "Trailer":"https://www.youtube.com/watch?v=Mg2JD7HQr8g",
    "Duracion": 112,
    "Fecha": 2012,
    "Genero":["Drama","Comedia"],
    "Descripcion":"Historia basada en hechos reales, sobre dos hombres que nunca deberían haberse encontrado: un aristócrata herido en un accidente y un joven de los suburbios de París quien se convierte en su asistente y le devuelve las ganas de vivir.",
    "Valoracion":0,
    "Resena":[],
    },
    {
    "Portada":"https://www.abc.es/media/peliculas/000/048/979/insidious-la-ultima-llave-2.jpg",
    "Nombre":"Insidious: La Ultima Llave",
    "Trailer":"https://www.youtube.com/watch?v=lUwaosQZkHU",
    "Duracion": 103,
    "Fecha": 2018,
    "Genero":["Terror"],
    "Descripcion":"La parapsicóloga Elise Rainier afronta su caso sobrenatural más terrorífico: en su propia casa.",
    "Valoracion":0,
    "Resena":[],
    },
    {
    "Portada":"https://i0.wp.com/imgs.hipertextual.com/wp-content/uploads/2022/09/Smile.png?fit=1400%2C698&quality=50&strip=all&ssl=1",
    "Nombre":"Smile",
    "Trailer":"https://www.youtube.com/watch?v=u7h4v79F0L4",
    "Duracion": 115,
    "Fecha": 2022,
    "Genero":["Terror"],
    "Descripcion":"Tras presenciar un extraño y traumático incidente con un paciente, la doctora Rose Cotter (Sosie Bacon) comienza a experimentar sucesos aterradores que no puede explicar. A medida que un terror abrumador comienza a apoderarse de su vida, Rose debe enfrentarse a su problemático pasado para sobrevivir y escapar de su horripilante nueva realidad.",
    "Valoracion":0,
    "Resena":[],
    },
    {
    "Portada":"https://cdn.hobbyconsolas.com/sites/navi.axelspringer.es/public/media/image/2022/12/terrifier-2-2906918.jpg?tf=3840x",
    "Nombre":"Terrifier",
    "Trailer":"https://www.youtube.com/watch?v=vTutJ2_E1Vo",
    "Duracion": 81,
    "Fecha": 2022,
    "Genero":["Terror"],
    "Descripcion":"El payaso psicópata Art aterroriza a dos chicas durante la noche de Halloween, matando a todos aquellos que se interponen en su camino.",
    "Valoracion":0,
    "Resena":[],
    },
    {
    "Portada":"https://upload.wikimedia.org/wikipedia/commons/a/a8/Escape_Room_-_%22The_Expedition%22_%28Escape_Quest_Bethesda%29.jpg",
    "Nombre":"Escape Room",
    "Trailer":"https://www.youtube.com/watch?v=9C1V8XPBlkw",
    "Duracion": 86,
    "Fecha": 2019,
    "Genero":["Terror"],
    "Descripcion":"Seis amigos prueban su inteligencia en un cuarto de escape, pero el juego toma un giro oscuro y ahora tienen una hora para resolver los acertijos necesarios para lograr escapar de la habitación con vida.",
    "Valoracion":0,
    "Resena":[],
    },
    {
    "Portada":"https://www.espinof.com/criticas/sitges-2021-ultima-noche-soho-brillante-edgar-wright-refina-su-estilo-thriller-psicologico-descomunal",
    "Nombre":"Ultima noche en el soho",
    "Trailer":"https://www.youtube.com/watch?v=qwpVk8-JGvw",
    "Duracion": 118,
    "Fecha": 2021,
    "Genero":["Terror"],
    "Descripcion":"El último thriller psicológico del aclamado director Edgar Wright. Eloise, una aprendiz a diseñadora de moda, es capaz de volver de misteriosamente a los años 60, donde se encuentra con una deslumbrante aspirante a cantante, Sandie. Pero el Londres de los sesenta no es lo que aparenta y en el Soho empezarán a resquebrajarse los sueños del pasado.",
    "Valoracion":0,
    "Resena":[],
    },
    {
    "Portada":"https://hips.hearstapps.com/hmg-prod/images/la-novia-2015-inma-cuesta-1558104145.jpg",
    "Nombre":"La novia",
    "Trailer":"https://www.youtube.com/watch?v=SASmPFHqDX0",
    "Duracion": 91,
    "Fecha": 2017,
    "Genero":["Terror"],
    "Descripcion":"La joven Nastya va al pueblo natal de su novio Ivan para conocer a su familia. Allí se da cuenta que los familiares de Ivan son muy extraños y el lugar está lleno de espeluznantes fotografías. Nastya lucha por calmarse esperando casarse pronto y ser feliz junto a su amado. Pero Ivan desaparece y ella acaba siendo preparada para una misteriosa ceremonia que debe llevarse a cabo antes de la boda",
    "Valoracion":0,
    "Resena":[],
    },
    {
    "Portada":"https://pics.filmaffinity.com/La_bruja-169933530-large.jpg",
    "Nombre":"La bruja",
    "Trailer":"https://www.youtube.com/watch?v=X_exzE_l-t0",
    "Duracion": 88,
    "Fecha": 2016,
    "Genero":["Terror"],
    "Descripcion":"En esta increíble y aterradora película, los eternos conceptos de brujería, magia negra y posesión se unen de una forma innovadora para contar la fascinante historia de la desintegración de una familia asentada en el campo de Nueva Inglaterra.",
    "Valoracion":0,
    "Resena":[],
    },
    {
    "Portada":"https://pics.filmaffinity.com/Host-620972115-large.jpg",
    "Nombre":"Host",
    "Trailer":"https://www.youtube.com/watch?v=nA5CZGiPSoo",
    "Duracion": 56,
    "Fecha": 2020,
    "Genero":["Terror"],
    "Descripcion":"En pleno confinamiento, un grupo de amigas quedan para realizar una sesión de espiritismo a través de Zoom. El ambiente se enrarece cuando alguien (o algo) más se une a la llamada...",
    "Valoracion":0,
    "Resena":[],
    },
    {
    "Portada":"https://images.ecestaticos.com/OU4qzwaeq335zKh4TxYJ6XibrXw=/39x0:1123x609/1200x675/filters:fill(white):format(jpg)/f.elconfidencial.com%2Foriginal%2F7be%2Faa1%2F87d%2F7beaa187d3d7cc5e0fb678eec0f768d3.jpg",
    "Nombre":"Annabelle vuelve a casa",
    "Trailer":"https://www.youtube.com/watch?v=1VTnFrWGD-w",
    "Duracion": 101,
    "Fecha": 2019,
    "Genero":["Terror"],
    "Descripcion":"Tras encerrarla en una vitrina sagrada en la sala de artefactos de los Warren, Annabelle despierta a los espíritus a su alrededor, y se centrarán en la hija de los Warren y sus amigas.",
    "Valoracion":0,
    "Resena":[],
    },
    {
    "Portada":"https://areajugones.sport.es/wp-content/uploads/2019/10/It-Chapter-two.jpg",
    "Nombre":"IT Capítulo 2",
    "Trailer":"https://www.youtube.com/watch?v=o1sQbtZpsic",
    "Duracion": 169,
    "Fecha": 2017,
    "Genero":["Terror"],
    "Descripcion":"Cada 27 años el terror visita de nuevo Derry, en Maine. «IT Capítulo 2» reúne a los protagonistas casi 30 años después de los eventos de la primera película.",
    "Valoracion":0,
    "Resena":[],
    },
    {
    "Portada":"https://pics.filmaffinity.com/meet_cute-379171303-large.jpg",
    "Nombre":"Una cita casi perfecta",
    "Trailer":"https://www.youtube.com/watch?v=-ahFzMg_9C8",
    "Duracion": 90,
    "Fecha": 2022,
    "Genero":["Romance", "Drama"],
    "Descripcion":"Cuando Sheila y Gary se conocen, surge el amor a primera vista, hasta que nos damos cuenta de que su cita mágica no es cosa del destino. Sheila ha estado viajando en una máquina del tiempo y se han enamorado una y otra vez. Pero cuando la noche perfecta deja de serlo, Sheila viaja al pasado de Gary para transformarlo en su hombre perfecto.",
    "Valoracion":0,
    "Resena":[],
    },
    {
    "Portada":"https://s2.ppllstatics.com/elcorreo/www/multimedia/202110/19/media/cortadas/After28-kA1-U1701083391960OzE-1248x770@El%20Correo.jpg",
    "Nombre":"After. Amor Infinito",
    "Trailer":"https://www.youtube.com/watch?v=bVjSl_AGSPQ",
    "Duracion": 95,
    "Fecha": 2022,
    "Genero":["Romance", "Drama"],
    "Descripcion":"El amor de Tessa (Josephine Langford) y Hardin (Hero Fiennes Tiffin) nunca ha sido fácil. Ella es la única capaz de entenderle y calmarle y él la necesita, pero ella ya no es la chica buena y dulce que era cuando llegó a la universidad. Si quieren que su amor sobreviva, primero tendrán que trabajar en sí mismos. ¿Pero será su destino seguir estando juntos?",
    "Valoracion":0,
    "Resena":[],
    },
    {
    "Portada":"https://i.blogs.es/9dff4b/mebeforeyouf1/1366_2000.jpg",
    "Nombre":"Antes de ti",
    "Trailer":"https://www.youtube.com/watch?v=y-tS4DcM-Ug",
    "Duracion": 110,
    "Fecha": 2016,
    "Genero":["Romance", "Drama"],
    "Descripcion":"Un chica de una pequeña ciudad (Emilia Clarke) establece un improbable vínculo con un hombre recientemente paralizado (Sam Claflin) al que está cuidando.",
    "Valoracion":0,
    "Resena":[],
    },
    {
    "Portada":"https://pics.filmaffinity.com/Poliamor_para_principiantes-770357900-large.jpg",
    "Nombre":"Poliamor para principiantes",
    "Trailer":"https://www.youtube.com/watch?v=Xhf42Qh9wyk",
    "Duracion": 94,
    "Fecha": 2021,
    "Genero":["Romance", "Comedia"],
    "Descripcion":"Manu, 28 años, es un friki romántico e intento de youtuber que aún vive con sus padres. Conoce a Amanda, doctora que practica el poliamor, de la que no puede evitar enamorarse. Tendrá pues que pelearse por convertirse en protagonista de esta relación a 6 bandas. Esta experiencia amorosa impulsa su carrera en Youtube pero acabará poniendo en jaque su nueva relación.",
    "Valoracion":0,
    "Resena":[],
    },
    {
    "Portada":"https://www.lavanguardia.com/peliculas-series/images/movie/backdrop/2022/6/w1280/3PIF0u6ulHX9Se0DED4TCGXG4U2.jpg",
    "Nombre":"Primer Amor",
    "Trailer":"https://www.youtube.com/watch?v=oP1OgpgnT9Y",
    "Duracion": 96,
    "Fecha": 2022,
    "Genero":["Romance"],
    "Descripcion":"Una tierna mirada sobre la entrada en la edad adulta. Jim (Hero Fiennes Tiffin), en su último año en el instituto, vive los altibajos de su primer amor con Ann (Sydney Park), sabiendo que en breve partirán a la universidad. Entretanto, los padres de Jim (Diane Kruger y Jeffrey Donovan) sufren las vicisitudes de una crisis financiera en la familia.",
    "Valoracion":0,
    "Resena":[],
    },
    {
    "Portada":"https://www.eurochannel.com/images/stories/love_is_not_perfect_1.jpg",
    "Nombre":"El amor es imperfecto",
    "Trailer":"https://www.youtube.com/watch?v=qZQB4mWdhd8",
    "Duracion": 92,
    "Fecha": 2012,
    "Genero":["Romance", "Drama"],
    "Descripcion":"Elena es una hermosa mujer de 35 años con una obsesión enfermiza con la perfección. Su ordenada vida se convierte en un caos cuando conoce a Adriana, una joven de 18 años que ofrece pasión y emoción, y a Héctor, un hombre mayor que ofrece estabilidad y seguridad.",
    "Valoracion":0,
    "Resena":[],
    },
    {
    "Portada":"https://pics.filmaffinity.com/Bright_Star-620865224-large.jpg",
    "Nombre":"Bright Star",
    "Trailer":"https://www.youtube.com/watch?v=tNMZombPMpM",
    "Duracion": 114,
    "Fecha": 2009,
    "Genero":["Romance", "Drama"],
    "Descripcion":"Londres, 1818. Una relación secreta comienza entre el joven poeta inglés de 23 años, John Keats, y su vecina, Fanny Brawne, una extrovertida y elegante estudiante. La atípica pareja empieza mal, él viéndola a ella como una frívola impertinente, y ella en absoluto impresionada no sólo por su poesía, sino por la literatura en general.",
    "Valoracion":0,
    "Resena":[],
    },
    {
    "Portada":"https://elpalomitron.com/wp-content/uploads/2018/07/HISTORIA-MAMMA-MIA-EL-PALOMITR%C3%93N.jpg",
    "Nombre":"¡Mamma Mia!",
    "Trailer":"https://www.youtube.com/watch?v=7URVcVXFPmM",
    "Duracion": 109,
    "Fecha": 2008,
    "Genero":["Romance","Comedia"],
    "Descripcion":"Tienen el tiempo de su vida, con Meryl Streep y un elenco de estrellas en esta celebración innegable la diversión de las madres e hijas, viejos amigos y la familia recién encontrado!",
    "Valoracion":0,
    "Resena":[],
    },
    {
    "Portada":"https://www.lavanguardia.com/peliculas-series/images/movie/backdrop/2010/6/w1280/r4OqScx7hVXsG1obaJjJKJNaxHT.jpg",
    "Nombre":"The Twilight Saga: Eclipse",
    "Trailer":"https://www.youtube.com/watch?v=pW5D5eeF3bk",
    "Duracion": 123,
    "Fecha": 2010,
    "Genero":["Romance","Drama"],
    "Descripcion":"Ha llegado el momento. Bella (Kristen Stewart) tiene que decidirse entre Edward (Robert Pattinson) y Jacob (Taylor Lautner). El regreso de Victoria (Bryce Dallas Howard) y la aparición de un temible ejército de vampiros neófitos pondrán a Bella de nuevo en peligro y obligarán a que los Cullen y los hombres lobo formen una difícil alianza.",
    "Valoracion":0,
    "Resena":[],
    },
    {
    "Portada":"https://i0.wp.com/imgs.hipertextual.com/wp-content/uploads/2019/04/hipertextual-after-aqui-empieza-todo-2019172769-scaled.jpg?fit=2560%2C1707&quality=50&strip=all&ssl=1",
    "Nombre":"After: Aquí empieza todo",
    "Trailer":"https://www.youtube.com/watch?v=n1tsEQ7-U7o",
    "Duracion": 105,
    "Fecha": 2019,
    "Genero":["Romance","Drama"],
    "Descripcion":"Tessa es una joven estudiante, hija obediente y entregada novia pero, cuando comienza su primer año en la universidad, se enamora de Hardin, un adolescente con un oscuro secreto. Juntos se embarcan en una pasional y complicada relación.",
    "Valoracion":0,
    "Resena":[],
    },
    {
    "Portada":"https://cdn01.diarimes.com/uploads/imagenes/bajacalidad/2022/08/24/_tadeo_f1ec0d27.jpeg?17925670d5ddc169bc27083b34f32215",
    "Nombre":"Las aventuras de Tadeo Jones",
    "Trailer":"https://www.youtube.com/watch?v=vdiwHzshBvA",
    "Duracion": 91,
    "Fecha": 2012,
    "Genero":["Infantil","Comedia"],
    "Descripcion":"Debido a un malentendido, a Tadeo, un albañil soñador, lo confunden con un famoso arqueólogo y lo envían en una expedición al Perú. Con la ayuda de su fiel perro Jeff, una intrépida profesora, un loro mudo y un buscavidas, intentará salvar la mítica ciudad perdida de los Incas de una malvada empresa de cazatesoros.",
    "Valoracion":0,
    "Resena":[],
    },
    {
    "Portada":"https://occ-0-33-299.1.nflxso.net/dnm/api/v6/E8vDc_W8CLv7-yMQu8KMEC7Rrr8/AAAABX5oX6Rdk0rdkKOeMM7L0J2n0pYuQqJHafx1u9f7uz02SZTdquyPvZZT55PS3hE8d_DePTBf4E3M4n1dIA7vzKmfJHR-rqaCW-CH.jpg?r=a3c",
    "Nombre":"Shrek",
    "Trailer":"https://www.youtube.com/watch?v=CwXOrWvPBPk",
    "Duracion": 90,
    "Fecha": 2001,
    "Genero":["Infantil","Comedia"],
    "Descripcion":"Nunca has conocido un héroe como Shrek, el encantador ogro que ha acaparado la atención de todo el mundo con…¡El Mayor Cuento de Hadas Jamás Contado! Vuelve a vivir cada momento de las andanzas de Shrek para rescatar a la Princesa Fiona, con la ayuda de Asno, y conseguir a cambio la escritura de su amado pantano de manos de Lord Farquaad. ¡SHREK es una aventura que querrás ver una y otra vez!",
    "Valoracion":0,
    "Resena":[],
    },
    {
    "Portada":"https://s1.eestatic.com/2017/09/13/actualidad/actualidad_246488190_46541487_1706x960.jpg",
    "Nombre":"Charlie Y La Fábrica De Chocolate",
    "Trailer":"https://www.youtube.com/watch?v=BGem82vCZNM",
    "Duracion": 115,
    "Fecha": 2005,
    "Genero":["Infantil","Comedia"],
    "Descripcion":"Descubre campos de césped de azúcar en la Habitación de Chocolate, navega por un río de chocolate… Consigue tu ticket de oro para entrar en la sorprendente fábrica de golosinas...",
    "Valoracion":0,
    "Resena":[],
    },
    {
    "Portada":"https://youvalencia.com/wp-content/uploads/2016/11/Ballerina-004.jpg",
    "Nombre":"Ballerina",
    "Trailer":"https://www.youtube.com/watch?v=CDPcawduyy0",
    "Duracion": 89,
    "Fecha": 2017,
    "Genero":["Infantil","Comedia"],
    "Descripcion":"Felicia es una chica huérfana con gran determinación y un único sueño: convertirse en bailarina. Para ello contará con la ayuda de su amigo Víctor, un joven inventor junto al que compartirá muchas y divertidas aventuras en la mágica París.",
    "Valoracion":0,
    "Resena":[],
    },
    {
    "Portada":"https://images.hola.com/us/images/0261-10707ba5059b-92c64caf2c38-1000/horizontal-1150/the-croods-have-survived-their-fair-share-of-dangers-and-disasters.jpg",
    "Nombre":"Los Croods",
    "Trailer":"https://www.youtube.com/watch?v=h-woGn1FCM0",
    "Duracion": 99,
    "Fecha": 2013,
    "Genero":["Infantil","Comedia"],
    "Descripcion":"Un terremoto ha acabado con la cueva en la que vivía un clan cavernícola, por lo que se ven obligados a buscar una nueva guarida. En su periplo, dirigidos por el jefe de la tribu, Crug, vivirán numerosas aventuras, y conocerán a otros clanes. Estos, más evolucionados, les mostrarán el increíble poder de hacer fuego...",
    "Valoracion":0,
    "Resena":[],
    },
    {
    "Portada":"https://i.blogs.es/774e47/cartel-bebe-jefazo/1366_2000.jpg",
    "Nombre":"El bebé jefazo. Negocios de familia",
    "Trailer":"https://www.youtube.com/watch?v=m8Aongzvh20",
    "Duracion": 107,
    "Fecha": 2021,
    "Genero":["Infantil","Comedia"],
    "Descripcion":"Puede que haya crecido y ahora sea un hombre de negocios y con dinero, pero Ted Templeton rememora su pasado de Bebé Jefazo cuando él y su hermano Tim recuerdan su rivalidad de niños, y hacen un sorprendente descubrimiento.",
    "Valoracion":0,
    "Resena":[],
    },
    {
    "Portada":"https://estaticos-cdn.elperiodico.com/clip/601f47b2-4be9-43b0-9be6-2089689f7e70_alta-libre-aspect-ratio_default_0.jpg",
    "Nombre":"Mascotas",
    "Trailer":"https://www.youtube.com/watch?v=imqzsiXcxdg",
    "Duracion": 90,
    "Fecha": 2016,
    "Genero":["Infantil","Comedia"],
    "Descripcion":"En su quinta colaboración para una película de animación, Illumination Entertainment y Universal Pictures presentan Mascotas, una comedia acerca de lo que hacen nuestras mascotas cuando cerramos la puerta de casa para afrontar nuestra rutina diaria.",
    "Valoracion":0,
    "Resena":[],
    },
    {
    "Portada":"https://is1-ssl.mzstatic.com/image/thumb/TPyQk8_hppmQYsH4nSKxVA/1200x675.jpg",
    "Nombre":"Trolls",
    "Trailer":"https://www.youtube.com/watch?v=dwSVxLssdVE",
    "Duracion": 93,
    "Fecha": 2016,
    "Genero":["Infantil","Comedia"],
    "Descripcion":"Únete a Poppy y Branch, en esta original aventura llena de música, color y buen rollo, para salvar a sus amigos del gigante Bergens. Incluye música original de Justin Timberlake.",
    "Valoracion":0,
    "Resena":[],
    },
    {
    "Portada":"https://www.abc.es/media/peliculas/000/021/967/madagascar-2.jpg",
    "Nombre":"Madagascar",
    "Trailer":"https://www.youtube.com/watch?v=HdQLfiPMAC8",
    "Duracion": 87,
    "Fecha": 2005,
    "Genero":["Infantil"],
    "Descripcion":"“¡Queremos marcha, marcha!” Es la canción de MADAGASCAR, la comedia más divertida del año, del estudio que te trajo Shrek y El Espantatiburones. Cuando 4 mimados animales del Zoo de Central Park de Nueva York naufragan por accidente en la exótica isla de Madagascar, descubren que realmente ¡esto es una jungla! Paco León, Alexis Valdés, Belén Rueda y Gonzalo de Castro ponen voz a estos animales.",
    "Valoracion":0,
    "Resena":[],
    },
    {
    "Portada":"https://images-na.ssl-images-amazon.com/images/S/pv-target-images/b75b1d311f711e2fc44dc6d5bcded1af4a61bc681f2c2f828e197fedce3cc9dd._RI_TTW_.jpg",
    "Nombre":"Alvin y las ardillas",
    "Trailer":"https://www.youtube.com/watch?v=lX2dFTRMVvQ",
    "Duracion": 91,
    "Fecha": 2007,
    "Genero":["Infantil","Comedia"],
    "Descripcion":"Tras probar suerte con un desesperanzado compositor, tres ardillas muy peculiares, Alvin, Simon y Theodore, deciden hacer de la casa de Dave, la suya propia. Enseguida las ardillas se dan cuenta de la necesidad de convencer a Dave de que las deje vivir allí para demostrarle que no sólo pueden andar como una persona, ¡sino que pueden cantar!",
    "Valoracion":0,
    "Resena":[],
    },
]
    


mongoose.connect('mongodb+srv://root:root@cluster0.oc2ykpm.mongodb.net/StreamHub?retryWrites=true&w=majority')
.then(async () => {
    const allPeliculas = await Pelicula.find()
    if(allPeliculas.length > 0){
        await Pelicula.collection.drop()
        console.log('Peliculas borrados')
    }
})
.catch(err => console.error('Error borrando',err))
.then(async() => {
    const peliculasMap = arrayPeliculas.map((pelicula) => new Pelicula(pelicula))
    await Pelicula.insertMany(peliculasMap)
    console.log('Peliculas añadidos');
})
.catch(err => console.error('Error insertando',err))
.finally(() => mongoose.disconnect());